### ISSUE TITLE
Error "Payload 'b10109000001003c0020' failed CRC and checksum"

### ISSUE THREAD

**Issue by lesgrebe** [mill1000/midea-ac-py#101]
Hello,
first of all, thank you for this great integration!

Since update from 2024.2.3 to 2024.3.1 everytime after Hass restart and also when HA is running an error occurs in the logger and constantly spamming the logger. I´ve tried it 2 times and in every case the error is shown in the log after HA restart an while HA is running. The integration (control the device) works without any problems. 

Device in use:
Midea real cool 35 (mobile aircondition)

Error-Log (Screenshot):
![image](https://github.com/mill1000/midea-ac-py/assets/37287548/a30f33d6-9fdb-4656-a995-9e8d22f29172)

Error-Log (Text):
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: msmart.device.AC.device
Quelle: custom_components/midea_ac/coordinator.py:38
Integration: Midea Smart AC (Dokumentation, Probleme)
Erstmals aufgetreten: 05:29:58 (1056 Vorkommnisse)
Zuletzt protokolliert: 09:00:44

Payload 'b10109000001003c0020' failed CRC and checksum. Received: 0x20, Expected: 0xBE or 0x8.
Payload 'b10109000001003c0000' failed CRC and checksum. Received: 0x0, Expected: 0xBE or 0x8.
Payload 'b1010900000100300000' failed CRC and checksum. Received: 0x0, Expected: 0xF3 or 0x14.

System in use (Raspberry Pi 4 8GB)
![image](https://github.com/mill1000/midea-ac-py/assets/37287548/d8650114-bfac-47a5-9ba1-d49b13ddc6de)

Maybe its an fault on my side but I didn´t change anything in my environment.
Would be great if there is an bugfix in an future update - thx. a lot!

Regards
Michi

**Comment by mill1000** [comment]
Hi. Thanks for using the integration and sorry about the trouble its causing.

If you don't mind, can you enable debug logging and post the full logs here?

After that, you can try downgrading to 2024.2.3 via HACS to resolve these warnings.

**Comment by lesgrebe** [comment]
Here the full logfile after enable debug logging. Hope this is helpful. Let me know if I can support you in any way...

[home-assistant_2024-03-13T16-08-44.830Z.log](https://github.com/mill1000/midea-ac-py/files/14590569/home-assistant_2024-03-13T16-08-44.830Z.log)

**Comment by mill1000** [comment]
Thanks!

My best guess is it's some device quirk/bug specific to the "new" protocol. The other packets have valid CRCs.

I figure the fix will be detecting when a device sends bad CRCs and disabling the check.

**Comment by mill1000** [comment]
I've got a fixed lined up for you in https://github.com/mill1000/midea-msmart/pull/114

Would you be comfortable testing this? It would require updating the msmart-ng package on your HA instance/container.

**Comment by lesgrebe** [comment]
Hmmm...thanks, but the problem is that I do not know how to update my container 😬. Would you be so kind and tell me how?

**Comment by mill1000** [comment]
I'll make it easy for you. I've merged the fix into the main branch. 

You can just use HACs to install the main branch instead of a specific release
![image](https://github.com/mill1000/midea-ac-py/assets/6924622/3a2e41e1-969a-4a8c-aa43-2f147769bdf4)

**Comment by lesgrebe** [comment]
Hi,
thanks for making my life easier ;)

I´ve installed the "main" branch and did some tests (turn on/off, changed modes fan_only/cool), changed fan speed and temperature) an no errors are logged. When I restartet HA an CRC related error occured a few minutes after restart, maybe its not depending to HA restart?!?

[home-assistant_2024-03-15T08-01-25.235Z.log](https://github.com/mill1000/midea-ac-py/files/14612552/home-assistant_2024-03-15T08-01-25.235Z.log)

It is not repeatable, sometimes after restart HA the error occurs and sometimes not. Unfortunately I forgot to enable debug messages. I will enable debug logging and stay on this "main" branch. If any error occurs i will report them...

Thx. a lot!

**Comment by lesgrebe** [comment]
Hi again,
now i have an CRC error logged with debug logging on. The error occurs during using the device (perform some tests).

[home-assistant_midea_ac_2024-03-15T08-22-16.597Z.log](https://github.com/mill1000/midea-ac-py/files/14612786/home-assistant_midea_ac_2024-03-15T08-22-16.597Z.log)

The CRC error does not constantly spamming the logger. Hope this logfile helps for further investigation.
Thx. for your effort!!!!

**Comment by lesgrebe** [comment]
Hi,

also got this error - Unfortunately debug logging was not enabled...

Error from Logger:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: msmart.device.AC.device
Quelle: custom_components/midea_ac/coordinator.py:38
Integration: Midea Smart AC (Dokumentation, Probleme)
Erstmals aufgetreten: 12:03:36 (1 Vorkommnisse)
Zuletzt protokolliert: 12:03:36

Payload 'b10109000001003c0000' failed CRC and checksum. Received: 0x0, Expected: 0xBE or 0x8.

Regards
Michi

**Comment by theshaww** [comment]
Same here. I just enabled debug logging.

**Comment by mill1000** [comment]
Thanks for the logs, at least there's a little improvement.

I guess the solution will need to be a little more involved.

**Comment by lesgrebe** [comment]
Let me know if you need anything (testing, debug logs,...). As mentioned above, I will stay on main branch till a newer update is available.

Thank you!

**Comment by mill1000** [comment]
Alright just push another update to main that I hope will resolve those final CRC errors.

**Comment by lesgrebe** [comment]
Okay merci! I redownload the main branch again and report the results.

**Comment by lesgrebe** [comment]
Hi,

Good news, no errors since last "main" branch update. Several checks (HA restart, device use) performed 👍🏽. For me, you can mark this as closed and I will stay on this main branch till a newer version is available.

Now summer can come 😏

Thank you very much!!

**Comment by mill1000** [comment]
That's great to hear! Could you do me one favor and grab another debug log of the device running for about a minute?

There was one additional minor quirk I addressed and would like to confirm it's fixed

**Comment by lesgrebe** [comment]
For sure, you will get this debug log in about 5-10 minutes.

**Comment by lesgrebe** [comment]
I´ve turned on the device in AUTO MODE and change to FAN_ONLY and change some other parameters like temperature, swing mode on/off, swing position, fan speed high/auto and back again till I turned the device off.

Debug-Log:
[home-assistant_midea_ac_2024-03-16T07-03-19.629Z.log](https://github.com/mill1000/midea-ac-py/files/14622737/home-assistant_midea_ac_2024-03-16T07-03-19.629Z.log)

Let me know if i can do more for you!

**Comment by mill1000** [comment]
Released in 2023.4.2
