### ISSUE TITLE
Update manifest to direct reports here

### ISSUE THREAD

**Issue by jamincollins** [mill1000/midea-ac-py#105]
Since you appear to be maintaining a more up to date version of the integration, you may want to update the manifest to direct users to report bugs here.

Specifically these sections:
```
custom_components/midea_ac/climate.py:https://github.com/mac-zhou/midea-ac-py
custom_components/midea_ac/manifest.json:        "documentation": "https://github.com/mac-zhou/midea-ac-py",
custom_components/midea_ac/manifest.json:        "issue_tracker": "https://github.com/mac-zhou/midea-ac-py/issues",
custom_components/midea_ac/manifest.json:        "codeowners": ["@mac-zhou"],
```

**Comment by mill1000** [comment]
Hi, not sure where you're looking. I updated the manifest long ago.

https://github.com/mill1000/midea-ac-py/blob/main/custom_components%2Fmidea_ac%2Fmanifest.json#L9-L11

**Comment by jamincollins** [comment]
Sorry, this was an error on my part with updating from the older source.
