### ISSUE TITLE
[Feature request] Separate strings for Vertical and Horizontal positions

### ISSUE THREAD

**Issue by v1k70rk4** [mill1000/midea-ac-py#109]
Hello,

if it's not too much work, is it possible to have separate strings in the following way:

```
"select": {
  "horizontal_swing_angle": {
    "state": {
      "off": "Off",
      "pos_1": "Left",
      "pos_2": "Left-center",
      "pos_3": "Center",
      "pos_4": "Right-center",
      "pos_5": "Right"
    }
  }
}
```
```
"select": {
  "vertical_swing_angle": {
    "state": {
      "off": "Off",
      "pos_1": "Top",
      "pos_2": "Top-center",
      "pos_3": "Center",
      "pos_4": "Bottom-center",
      "pos_5": "Bottom"
    }
  }
}
```
I can't say whether this is the case for all air conditioners :) But for my air conditioners, it's like this.

**Comment by mill1000** [comment]
@parautenbach, @gapple You've both also used the fan position selection. Do the above values work for your units too?

**Comment by parautenbach** [comment]
I don't see an HA service call for swing position. Am I missing it or is there another call to use?

**Comment by mill1000** [comment]
Not a service. Just the select entity (e.g. dropdown) for selecting the fan position. Currently it's using generic values like Position 1, Position 2, etc.

**Comment by v1k70rk4** [comment]
Hi, one of my air conditioners is working fine, but the other one doesn't display any of the settings. It also supports both adjustment modes from the app.
This is what it looks like in HA:
![image](https://github.com/mill1000/midea-ac-py/assets/120401244/75402966-1f7e-468a-a329-eb4d2ec20a02)

**Comment by mill1000** [comment]
@v1k70rk4 can you enable debug logs and post them? You'll have to tell me which device isn't showing the swing angle settings.

**Comment by parautenbach** [comment]
> Not a service. Just the select entity (e.g. dropdown) for selecting the fan position. Currently it's using generic values like Position 1, Position 2, etc.

Ah, got it: Not the entity popup, but from the devices page. I tested it on my unit that supports both swing modes and the numbered presets work just fine.

**Comment by mill1000** [comment]
Sorry, my request wasn't clear.

On your units, do the swings positions match the proposed strings in the first post?

i.e. For horizontal swing, is Position 1 the "Left" direction on your device? Is Position 5 the right?

For vertical swing, is Position 1 the top, and position 5 the bottom?

**Comment by parautenbach** [comment]
Right!

The positions work correctly as you want it to: horizontal 1 is left and 5 is right; vertical 1 blows straight in front and 5 blows down. 

I did pick up two issues now:
* When selecting off for either horizontal or vertical, the swing doesn't stop (it was on both and I tested it twice). 
* Beep is turned off, but the swing positions beep when selecting other options don't.

**Comment by mill1000** [comment]
Ok. I've got a PR to add unique strings for horizontal and vertical swing angle (#110).

> Beep is turned off, but the swing positions beep when selecting other options don't.

I've created another issue to track this here: https://github.com/mill1000/midea-msmart/issues/119

> When selecting off for either horizontal or vertical, the swing doesn't stop (it was on both and I tested it twice).

Can you clarify the exact steps? Are you selecting "Off" in the Swing Angle select entity or in the Climate Swing Mode?

**Comment by parautenbach** [comment]
> > When selecting off for either horizontal or vertical, the swing doesn't stop (it was on both and I tested it twice).
> 
> Can you clarify the exact steps? Are you selecting "Off" in the Swing Angle select entity or in the Climate Swing Mode?

1. Set swing mode to both: swing mode setting. 
2. Set either horizontal or vertical to off: swing angle setting. 
3. Remains swinging.

**Comment by mill1000** [comment]
Ah ok, thank you. That's not surprising since they're unrelated settings in the protocol.

I'll have to thing about this one for a bit to see how it makes sense for them to interact.

**Comment by mill1000** [comment]
Ok so I haven't had time to actually experiment with this yet but I'll describe what I'm wary of.

In this situation:

> 1. Set swing mode to both: swing mode setting.
> 2. Set either horizontal or vertical to off: swing angle setting.

I expect that enabling vertical swing would set vertical swing angle to "Off". I assume the settings are mutually exclusive, and the device would enforce this. i.e. Setting a swing angle sets it's corresponding swing mode to Off, and visa-versa. If this is not the case I think there's a bug to be addressed in msmart-ng.

So assuming the swing angle select is in the "Off" position already, does HA even trigger an event when the user selects "Off" again? 

If it doesn't, there's not much that can be done.

If it does, we have the option of disabling the swing mode, but then we're intermixing controls that (at the protocol level) are independent.

Another thought, both controls have "Swing" in their name. Would renaming the swing angle controls help reduce confusion around them? If "Swing angle" was renamed to "Fan position" would it help decouple the idea that setting it "Off" would affect Swing mode? Or should the string "Off" be replaced with something like "Disabled" or "Auto".

Unfortunately I don't have a unit capable of such feature so I can't really explore what the OEM applications do.

Anyway. Just some ramblings.

**Comment by parautenbach** [comment]
Luckily, this is more of a UX annoyance than a real problem. 

I think renaming could help, but I'd take another direction: include "automatic" in the swing mode name. It becomes quite long then. Alternatively, remove swing from the to set position options, as swing makes it sound automatic. Perhaps just "vertical angle setting" and "horizontal angle setting"?

To me, the 4 settings are actually interconnected (in my mind) in pairs of 2

I can check what the unit does using the remote. 

What would a good test sequence be?

Maybe I should first better articulate the issue. 

In my test, I had fixed settings selected, and then switched is swing back to both (automatic swinging). 

This is what I said then:

> 1. Set swing mode to both: swing mode setting.
> 2. Set either horizontal or vertical to off: swing angle setting.
> 3. Remains swinging.

I think, what I'd expect if automatic swinging for a given direction is active, then the fixed position setting must be displayed as off, instead of the last selected fixed position. The issue that I can imagine, is that if that is set, it might stop the automatic swinging. 

Revised:
1. Set swing mode to both: swing mode setting.
2. Check swing angle setting: both must be off.

Similarly, I guess I need to test:
1. Set fixed positions. 
2. Turn on automatic swinging for one or both directions.
3. Check the fixed setting: Does it still display the previously fixed position, or does it show as off?

**Comment by mill1000** [comment]
Ok, thanks for the information.

> I think, what I'd expect if automatic swinging for a given direction is active, then the fixed position setting must be displayed as off, instead of the last selected fixed position. The issue that I can imagine, is that if that is set, it might stop the automatic swinging.

Yes I agree, this should be the behavior. I've created another issue to track this problem. #122

**Comment by mill1000** [comment]
@parautenbach I released a new version that should fix the swing mode vs swing angle interaction. Are you still seeing any odd interactions between these two functions?

**Comment by parautenbach** [comment]
> @parautenbach I released a new version that should fix the swing mode vs swing angle interaction. Are you still seeing any odd interactions between these two functions?

It works!  Thanks! :-) 

I tested a few cases:
1. Turn on; swing mode both; set vertical angle: swing mode is now horisontal. 
2. Swing mode both; set horizontal angle: swing mode is now vertical.
3. Set swing mode back to both: angles are both set to off.
