### ISSUE TITLE
The option to adjust the vertical and horizontal angles is not visible

### ISSUE THREAD

**Issue by v1k70rk4** [mill1000/midea-ac-py#119]
Hello, one of my air conditioners' app can adjust the vertical and horizontal angle of its blade, but the integration does not recognize this. I have attached a debug log. Thanks in advance for checking what the issue might be. Let me know if you need anything else.

Yes, 'anion' refers to turning on ionization. I would really appreciate this feature as well, because an IR transmitter/receiver was installed just to enable it. :)

Midea breezless+
[midea breezless.txt](https://github.com/mill1000/midea-ac-py/files/15152944/midea.breezless.txt)

**Comment by mill1000** [comment]
Hm... based on the capabilities your device doesn't claim to support swing/fan angle. However, it wouldn't be the first time a device misrepresented it's capabilities.

Only away around this might be to add a configuration option to force certain features to be available.

**Comment by v1k70rk4** [comment]
It's really a good idea to have an option to allow everything regardless of whether it recognizes suitability.

If there will be such a version, I will give feedback on how it works.

By the way, I have a climate-specific LUA script, I'm not sure if it helps anything but I'll upload that too.
[T_0000_AC_00000Q19_2023072401.lua.txt](https://github.com/mill1000/midea-ac-py/files/15166356/T_0000_AC_00000Q19_2023072401.lua.txt)

**Comment by mill1000** [comment]
Thanks for the Lua. It matches the existing one I have here: https://github.com/mill1000/midea-msmart/blob/main/reference/T_0000_AC_00000Q1B_2023072401.lua

Another method to determine support might be to query the properties (e.g. vertical & horizontal angle), and check the response. I'm assuming unsupport features will not be responded to.

**Comment by v1k70rk4** [comment]
I really like how you're approaching the plugin. However, Midea air conditioners are quite strange. I have three identical air conditioners and one Breezless.
Out of the three identical ones, one behaves completely differently, for example, it requires a 1-second pause between commands because the device freezes :D
There's another interesting thing: one of the three can't turn off the display via app (according to its own app), but with this plugin, I can easily turn it off.

It's possible that you're putting a lot of energy into determining whether it can do something or not, but it might be enough to leave it up to the user. Although you said in one comment that you have an air conditioner that can't adjust angles, this is easily testable by seeing if you get a response.

In most plugins, extra features can be added individually and anything that doesn't work can be turned off. But I've also encountered plugins that throw in everything they can handle and the user just disables what doesn't work on their device.

From the branch you forked this from, I believe features can be added one by one. But, for example, he didn't manage to adjust the blade angle :) and I've been messing with Infrared commands to get it to work until now.

**Comment by mill1000** [comment]
Thanks for your feedback. I appreciate it. You're an excellent user for testing since you appear to have all sorts of hardware available to you.
 
> In most plugins, extra features can be added individually and anything that doesn't work can be turned off. But I've also encountered plugins that throw in everything they can handle and the user just disables what doesn't work on their device.

My philosophy is to only show the options that I know should work, and then optionally give power users to turn on functionality the device doesn't claim to support. I think this approach would limit the amount of issues that get created when a new user mistakenly thinks their device is capable of every feature.

> Although you said in one comment that you have an air conditioner that can't adjust angles, this is easily testable by seeing if you get a response.

My devices don't support fan angle/position so I need to test this theory on them.

**Comment by v1k70rk4** [comment]
Hi, I am wondering if there is a command I can issue to msmart-ng to adjust the blade angle? Or is this more complicated? Can I help with this somehow?

**Comment by mill1000** [comment]
You could use [pyscript](https://github.com/custom-components/pyscript) to run custom scripts/services that set the angle via msmart-ng

**Comment by mill1000** [comment]
I've created a new issue to track this request #138
