### ISSUE TITLE
The Anion support isn't working.

### ISSUE THREAD

**Issue by v1k70rk4** [mill1000/midea-ac-py#128]
Hello,

My air conditioner is acting quite strangely. If ionization is on, switching the toggle disables this function regardless of whether I turn it on or off.

I made a debug log:
1. Enabled the anion function in HA
2. Disabled the anion function in HA
3. Enabled the anion function in the app
4. Disabled the anion function in the app
5. Enabled the anion function in the app again
6. Enabled the anion function in HA (which turned off the air conditioner)
7. Turned it off in HA

[midea_msmart.debug_anion.log](https://github.com/mill1000/midea-ac-py/files/15227313/midea_msmart.debug_anion.log)

**Comment by mill1000** [comment]
Thanks for testing it. Something seems quite off. I'll have to examine the logs again.

**Comment by mill1000** [comment]
Ok, looks like I really botched this anion feature. Your device (and another users #131) is interpreting the anion property (0x021E) as an "eco state" property (0x001E).

But upon further review of the Lua and JS available to me, it appears this Anion property is never actually used and instead it's using a "purifier" function. This might be the ION+UV option you described.

**Comment by v1k70rk4** [comment]
https://github.com/mill1000/midea-msmart/issues/124#issuecomment-2100484666

**Comment by mill1000** [comment]
I think we've got this one solved in 2024.5.1. Please re-open if it's not working still.

**Comment by v1k70rk4** [comment]
It works perfectly! And it also clearly shows up in HA when I switch it from the remote.
