### ISSUE TITLE
 2024.5.0 - Unknown property. ID: 0x  1E, Size: 4. 

### ISSUE THREAD

**Issue by RXM307** [mill1000/midea-ac-py#131]
Since Upgrading recently I'm getting these errors streaming in my HA logs, I think I was previously running 2024.2.x but I think I was seeing the same logs since 2024.4.x

[msmart.device.AC.command] Unknown property. ID: 0x  1E, Size: 4.

**Comment by mill1000** [comment]
Thanks for reporting and sorry for the noise in your logs. I've seen similar in another users log and will get a fix out shortly

**Comment by mill1000** [comment]
This warning should no longer occur with 2024.5.1
