### ISSUE TITLE
half-degree Temperature Step?

### ISSUE THREAD

**Issue by quentinwolf** [mill1000/midea-ac-py#135]
Hello!

I recently swapped to your integration from the other 'Midea AC LAN' one, as I saw your integration allowed to enable/disable the beep which I think is a pretty significant reason to change, allowing Home Assistant to control the AC silently is great, although in the configuration for each of my AC's, I have the "Temperature Step" set to 0.5, but the integration doesn't seem to honor this and instead steps the temperature in 1c increments.

The other integration allowed 0.5 temperature steps, while the display on the AC unit itself doesn't have a decimal spot (20/21/22/23), the unit still accepted 0.5 degree increments and would remember that when powered off/on, so going  20, 20.5, 21, 21.5, 22, etc, would seem to round down on the display (20/20/21/21/22) when adjusting the temperature, but still seemed to honor the 0.5 difference.

Just wondering if this is something that could be implemented for a bit better precision in temperature adjustment?

**Comment by quentinwolf** [comment]
Actually you may be able to close this.  I'm not sure if it's your integration or a hiccup with the Simple Thermostat card, as tapping the temperature brings up the more standard dial and lets me change in half degree increments.  Just thought I'd provide a follow-up so you're not trying to chase down an issue that may not actually exist. :)

**Comment by quentinwolf** [comment]
Closing this out as it's not an issue, I overlooked adding the "step_size: 0.5" to the Simple Thermostat's YAML.  My apologies!  Great work with this integration! :)

**Comment by mill1000** [comment]
Hey glad it's working well for you. Feel free to reach out if you've got any other issues.
