### ISSUE TITLE
Device became unavailable 

### ISSUE THREAD

**Issue by FaceStealerrog** [mill1000/midea-ac-py#137]
Hi,

I'm using this integration to connect my inventor units and most of the time it works greats. But i noticed in the log files that the 3 devices often became unavailable... sometimes for minutes. Is this a known issue and so yes can I resolve this?

**Comment by mill1000** [comment]
Are you blocking the devices from internet access? Other users have reported issues with their devices when they have.

Are the device becoming unavailable at regular intervals? Some devices need the `Maximum Connection Lifetime` configured to prevent going unavailable at regular intervals, usually 2-3 minutes.

**Comment by FaceStealerrog** [comment]
Hi,

Thanks for your quick response! I'm not blocking any internet access. How long should i configure, 90 seconds?

**Comment by mill1000** [comment]
It would be best to start with some debug logs of your devices when they go unavailable.

**Comment by bharvey88** [comment]
fwiw i was having the same issue. I just set it to 30seconds and it stopped reconnecting every ~2minutes. 

in the logs i just see a bunch of failed connections and transport errors. I believe there's actually a bug here but i'm not sure.

in the debug logs i see lots of ```2024-05-21 13:30:26.992 ERROR (MainThread) [msmart.base_device] Network error 192.168.1.78:6444: Transport is closing or closed.``` and ```Unsupported packet: f28758727334de2b858f36748a5aa95af0907f11f4cb5439f1cb2fe21f0d7e0cf8fd91b21bb93b5ae8fcb9156b3456d69742fe36069ca61bff6ca3c95d6eb8f2
2024-05-21 14:27:15.015 ERROR (MainThread) [msmart.base_device] Network error 192.168.1.78:6444: Error packet received.```

**Comment by mill1000** [comment]
Can you post your full logs? That `Unsupported packet` message is particularly interesting.

**Comment by bharvey88** [comment]
> Can you post your full logs? That `Unsupported packet` message is particularly interesting.

I didnt post the full file cuz it has sensitive data that wasnt stripped from frigate and i wasnt sure about possibly leaking a token or some other info with this integration as well. I can try to sanitize and then upload in a few

**Comment by mill1000** [comment]
There's nothing really sensitive in this integration logs, so if you can filter to them to this integration and msmart only you'll be good.

**Comment by bharvey88** [comment]
[home-assistant_midea_ac_2024-05-22T01-53-35.167Z.log](https://github.com/mill1000/midea-ac-py/files/15398063/home-assistant_midea_ac_2024-05-22T01-53-35.167Z.log)

i believe during this test i changed `Maximum Connection Lifetime` to 300 seconds and reloaded the integration.

**Comment by mill1000** [comment]
Looks like none of the really interesting errors (the `unsupported packet`) occurred while your debug logging was enabled.

I also see that you have the `midea_ac_lan` integration installed. Two copies of it somehow. Can you ensure that integration is not configured to talk to the device in question.

**Comment by bharvey88** [comment]
It’s not  using that custom component I moved to yours. I’ll remove it and
capture more logs. Wil turning it on/off help? What should I set the
timeout to in configure? Leave it blank so errors occur? FWIW I do not
believe I observed this behavior of going unavailable with the other custom
component.

**Comment by mill1000** [comment]
> Wil turning it on/off help? What should I set the timeout to in configure? Leave it blank so errors occur?

I guess leave it blank for now. No need to turn the device on/off, just let the integration run for 10-15 minutes (or until you have issues with the `unsupported packet` messages).

> FWIW I do not believe I observed this behavior of going unavailable with the other custom component.

Can't speak for `midea_ac_lan` but the original `midea_ac_py` pretty much just suppressed all network errors.

**Comment by patrykwoj91** [comment]
Hello,
I am using Your integration since few days with my MDV Aroma (Midea AC group) and I also face the issue with unavailability for both my units:

```
2024-05-22 23:40:37.156 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Transport is closing or closed.
2024-05-22 23:40:49.189 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Transport is closing or closed.
2024-05-22 23:42:52.213 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Transport is closing or closed.
2024-05-22 23:43:05.039 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Transport is closing or closed.
2024-05-22 23:45:07.216 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Transport is closing or closed.
2024-05-22 23:45:20.039 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Transport is closing or closed.
2024-05-22 23:47:22.214 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Transport is closing or closed.
2024-05-22 23:47:35.040 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Transport is closing or closed.
2024-05-22 23:49:37.165 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Transport is closing or closed.
```

**Comment by FaceStealerrog** [comment]
Hi,

Sorry for my late response!

I did what @mill1000 said to do. And raised the Maximum Connection Lifetime to: 90sec

The connection is now stable, Thanks! 

I only have some modes that are not working. For example, I cannot set the rotation of the fan. Neither can I change the position. No idea what causes this.

**Comment by mill1000** [comment]
> Should I give it a try with MaximumConnectionLifetime set to something like 2 minutes?

@patrykwoj91 Try 90 seconds. That seems like a good number for multiple people.


> The connection is now stable, Thanks!

Well that's good to hear.

> I only have some modes that are not working. For example, I cannot set the rotation of the fan. Neither can I change the position. No idea what causes this.

Are these things supported by the OEM app for your device? If so, please enable debug logging, restart HA or reload the integration, and create a new issue.

**Comment by FaceStealerrog** [comment]
Hi @mill1000,

Yes this is supported by the OEM app. I will investigate some more and create a new issue if necessary. Thanks!

**Comment by bharvey88** [comment]
> > Should I give it a try with MaximumConnectionLifetime set to something like 2 minutes?
> 
> @patrykwoj91 Try 90 seconds. That seems like a good number for multiple people.
> 
> > The connection is now stable, Thanks!
> 
> Well that's good to hear.
> 
> > I only have some modes that are not working. For example, I cannot set the rotation of the fan. Neither can I change the position. No idea what causes this.
> 
> @FaceStealerrog Are these things supported by the OEM app for your device? If so, please enable debug logging, restart HA or reload the integration, and create a new issue.

For fun i deleted my device and added it again from the integration. I noticed that when adding it this time, it got two new entities number.upstairs_ac_fan_speed and switch.upstairs_ac_purifier which both stay unavailable just like the other user.



> > Wil turning it on/off help? What should I set the timeout to in configure? Leave it blank so errors occur?
> 
> I guess leave it blank for now. No need to turn the device on/off, just let the integration run for 10-15 minutes (or until you have issues with the `unsupported packet` messages).
> 
> > FWIW I do not believe I observed this behavior of going unavailable with the other custom component.
> 
> Can't speak for `midea_ac_lan` but the original `midea_ac_py` pretty much just suppressed all network errors.

[home-assistant_midea_ac_2024-05-23T20-47-55.071Z.log](https://github.com/mill1000/midea-ac-py/files/15422517/home-assistant_midea_ac_2024-05-23T20-47-55.071Z.log)
15 minutes of debug logs attached!

**Comment by mill1000** [comment]
>  I noticed that when adding it this time, it got two new entities number.upstairs_ac_fan_speed and switch.upstairs_ac_purifier which both stay unavailable just like the other user.

Is your device off? Certain entities are unavailable when the device is off.

**Comment by bharvey88** [comment]
no the device was power cycled and turned on then added it was never turned off during the log captures

**Comment by bharvey88** [comment]
i have a very stable home assistant setup running on an 8th gen intel i7 on latest stable haos 12.3 and core 2024.5.4. 

ignore the recorder errors those are only there cuz i deleted the integration and added it again to start fresh and give you fresh logs. the warninga and errors are just saying it didnt merge some historical data when i renamed the device to the old device name.

**Comment by mill1000** [comment]
Just making sure we aren't dealing with an out of date core.

I'd recommend adding the following to your `configuration.yaml`, removing all devices and adding one back.

```
logs:
    custom_components.midea_ac: info
    msmart: debug
```

Hopefully that should catch enough information to see what's going on.

**Comment by bharvey88** [comment]
removing all devices of what? i only own one medea ac device

**Comment by mill1000** [comment]
* Remove all devices associated with this integration.

So just your one device then.

**Comment by mill1000** [comment]
tuckkern@gmail.com

**Comment by mill1000** [comment]
@bharvey88 Looked at the logs you sent and nothing was out of the ordinary. 

You do have regular disconnects about at the 2 minute mark (as you knew). So I would go back to the 90 second max connection lifetime.

**Comment by raddah** [comment]
Same issue on my side, any idea how to resolve this issue ? 

Or do I have to open another issue ?

**Comment by mill1000** [comment]
> Same issue on my side, any idea how to resolve this issue ? 
> 
> Or do I have to open another issue ? 

Have you tried setting the maximum connection lifetime?

**Comment by raddah** [comment]
> > Same issue on my side, any idea how to resolve this issue ? 
> > 
> > Or do I have to open another issue ? 
> 
> Have you tried setting the maximum connection lifetime?

Hi I have configured 90 second is there any preferred time to configured more? please suggest

**Comment by mill1000** [comment]
The correct value is device dependent, but 90 seconds is a common value.

**Comment by raddah** [comment]
I have done that configuration to 90 seconds still on the logs I can see `Became unavailable`  screenshot below

![Screenshot 2024-07-05 at 2 52 59 PM](https://github.com/mill1000/midea-ac-py/assets/7273511/4f93e10e-93dd-411d-81b3-4bf3cf8f9a05)

**Comment by raddah** [comment]
While I was checking the AC today I noticed Wi-Fi signal from AC split display become off when same time as Home assistant dashboard card what could be the issue if we can investigate it more.

![image](https://github.com/mill1000/midea-ac-py/assets/7273511/dc041b39-9425-4aa3-af35-09e908e83936)

**Comment by mill1000** [comment]
> While I was checking the AC today I noticed Wi-Fi signal from AC split display become off when same time as Home assistant dashboard card what could be the issue if we can investigate it more.

Are you blocking the device from accessing the internet? That can cause the WiFi to periodically reboot.

**Comment by raddah** [comment]
> > While I was checking the AC today I noticed Wi-Fi signal from AC split display become off when same time as Home assistant dashboard card what could be the issue if we can investigate it more.
> 
> 
> 
> Are you blocking the device from accessing the internet? That can cause the WiFi to periodically reboot.

No I didn't block it but still showing Became unavailable on the logs and still dashboard disappeared for 30 - 50 seconds. 


Is there any root cause for this appeared from recent issues when we do integration with Home Assistant? 


Device WiFi from Nethome

 ![image](https://github.com/mill1000/midea-ac-py/assets/7273511/b4a8d469-74f2-4501-b024-4284dc9fa6ab)

**Comment by mill1000** [comment]
> Is there any root cause for this appeared from recent issues when we do integration with Home Assistant?

Sorry I don't understand your question.

You need to provide full debug logs of the disconnect occurring for me to try to help.

**Comment by raddah** [comment]
> > Is there any root cause for this appeared from recent issues when we do integration with Home Assistant?
> 
> 
> 
> Sorry I don't understand your question.
> 
> 
> 
> You need to provide full debug logs of the disconnect occurring for me to try to help.

How can I provide to you the logs while option ```
-d
``` not in ```
msmart-g
``` 

I'll be happy to support.

**Comment by mill1000** [comment]
You can enable debug logging in Home Assistant on the integration page. Or you can enable it in your config YAML with
```
logger:
  default: warning
  logs:
    custom_components.midea_ac: info
    msmart: debug
```

**Comment by raddah** [comment]
[home-assistant_2024-07-20T20-30-44.395Z.log](https://github.com/user-attachments/files/16322279/home-assistant_2024-07-20T20-30-44.395Z.log)

Please see logs attached

**Comment by raddah** [comment]
Another logs after debug enabled from GUI also. 
[home-assistant_2024-07-21T01-33-07.403Z.log](https://github.com/user-attachments/files/16322773/home-assistant_2024-07-21T01-33-07.403Z.log)

**Comment by mill1000** [comment]
@raddah Ah..you're devices must be similar to the ones in #188. They don't respond to capability requests, which causes the first burst of errors. After that, everything appears to be working OK
