### ISSUE TITLE
Error setting up entry <device_name> for select

### ISSUE THREAD

**Issue by patrykwoj91** [mill1000/midea-ac-py#140]
Hello,
When configuration is changed via UI for devices, I receive following error in log:

`Rejestrator: homeassistant.config_entries
Source: config_entries.py:575

Error setting up entry MDV AC Gabinet for select
Error setting up entry MDV AC Salon for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 106, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 185, in async_setup_entry
    raise ValueError(
ValueError: Config entry MDV AC Gabinet (289e08de99e4fb13136a2ea2cd893ee2) for midea_ac.select has already been setup!`

Should I care about it? Or does it mean that config changes were not applied?

**Comment by mill1000** [comment]
I think this is due to a bug in HA that will be fixed in the next release. 

As far as I know it's harmless.

**Comment by mill1000** [comment]
Are you running HA 2024.5 or above?

**Comment by mill1000** [comment]
Could also be related to this PR #139. I realized I was failing to unload certain domains, so it's possible the error was the result of that.

**Comment by mill1000** [comment]
Closing as I believe this error should be resolved in 2024.5.4
