### ISSUE TITLE
Not able to connect AC anymore after HA upgrade to 2024.05.x

### ISSUE THREAD

**Issue by minosso** [mill1000/midea-ac-py#144]
After HA upgrade to 2024.05.x the device turned unavailable and I was not able to connect AC anymore, even if I try to add a new entry from Midea AC Integration.

##

Logger: msmart.base_device
Source: custom_components/midea_ac/coordinator.py:38
integration: Midea Smart AC (documentation, issues)
First occurred: June 7, 2024 at 9:56:31 PM (3696 occurrences)
Last logged: 12:13:38 PM

Network error 192.168.188.103:6444: Connect failed.
Network timeout 192.168.188.103:6444: Connect timeout.
No response from 192.168.188.103:6444 in 5.000000 seconds.

##

Logger: msmart.device.AC.device
Source: custom_components/midea_ac/__init__.py:64
integration: Midea Smart AC (documentation, issues)
First occurred: June 7, 2024 at 9:56:31 PM (5 occurrences)
Last logged: 12:02:37 PM

Failed to query device capabilities.

##

Logger: msmart.base_device
Source: custom_components/midea_ac/__init__.py:64
integration: Midea Smart AC (documentation, issues)
First occurred: June 7, 2024 at 9:56:31 PM (5 occurrences)
Last logged: 12:02:37 PM

Network error 192.168.188.103:6444: Connect failed.

**Comment by mill1000** [comment]
Hm..I'm not aware of any incompatibilities with HA 2024.5.  Based on the errors it looks like the device is not on the network/not responding.

Did the IP address change? When attempting to add a new device are you using automatic discovery, or manual configuration?

**Comment by minosso** [comment]
Yes, the IP address changed and I was unable to find were it was defined and how to change it.
After a long research I changed the config file </homeassistant/.storage/core.config_entries> then rebooted the HA

It will be great if you add the IP address information into web interface and some documentation how to change it.

**Comment by mill1000** [comment]
Glad you got it working.

> After a long research I changed the config file </homeassistant/.storage/core.config_entries> then rebooted the HA

I would've just removed and re-added the device.

> It will be great if you add the IP address information into web interface and some documentation how to change it.

I don't really anticipate changing the IP to be regularly required. I'll consider adding the configured IP in the device info or somewhere.
