### ISSUE TITLE
Add promp tone control.

### ISSUE THREAD

**Issue by Raouzer** [mill1000/midea-ac-py#145]
Hi,

Thank for this integration, any possibility to add the promp tone control ? :) 
The beeping sound at night is very annoying. This is a function that is normally addable.

Thanks in advance .

Regards

**Comment by mill1000** [comment]
Hi. This functionality is already implemented. :) It's configured under the integration options per device. e.g. click the "Configure" button next to the device when on the integration page

**Comment by Raouzer** [comment]
Ho my bad! Thanks you :)!

**Comment by mill1000** [comment]
No problem. Let me know if any other issues come up
