### ISSUE TITLE
Led control

### ISSUE THREAD

**Issue by smmarczak** [mill1000/midea-ac-py#146]
This works brilliantly for me. Love it. Would it be possible to add a control for the led temprature readout on my minisplit?

**Comment by mill1000** [comment]
Hi. Glad it's working well for you.

Does the display control switch not function for you? Some other users have reported being unable to control the LED with that switch (#34, #21, #6).

**Comment by smmarczak** [comment]
No, the display button just reverts back to on when I press it. Doesn't change it at the unit.

**Comment by mill1000** [comment]
Gotcha.

Does the OEM app support controlling the LED display?

**Comment by smmarczak** [comment]
Turns out it does! I usually use the remote.

**Comment by mill1000** [comment]
Oh excellent. I had an issue looking into alternate LED control messages ([midea-msmart/issues/53](https://github.com/mill1000/midea-msmart/issues/53)), but no one seemed to have a device that had app control of the LED.

To get started on this I'll need some debug log while you toggle the LED on/off via the app. You should wait 30 sec or so between each toggle.

**Comment by smmarczak** [comment]
Crap, I was wrong. Just got home and tested it, the button I thought was for it was for something else. Only controlled by remote.

**Comment by mill1000** [comment]
Oh bummer. Unfortunately in that case I don't think I'll be able to help. There's been a few other users who have similar devices.

You could hack something together with ESPHome to automate the LED via IR commands.
https://esphome.io/components/climate/midea.html#additional-control-options-using-ir-commands

**Comment by phreaq** [comment]
I am unable to turn off the led thru the integration, but I can turn it off with my remote (I'm currently use an IR blaster to control it).

I have logs that I can send you, if you'd like

**Comment by mill1000** [comment]
Can you turn it off with the OEM app?

**Comment by deezid** [comment]
I'm also stuck with using an IR blaster in Home Assistant to control the LED. Super annoying especially since there is no feedback if the LED is either off or on. But at least I got it into Home Assistant itself I guess. lol

**Comment by phreaq** [comment]
> Can you turn it off with the OEM app?

it seems I cannot, oh well, thanks

**Comment by mill1000** [comment]
Unfortunately it seems that would indicate it's not controllable over the network. So there doesn't appear to be any work I can perform.

I'm going to close this. Feel free to re-open if you think I should re-evaluate.
