### ISSUE TITLE
Outdoor temperature is reported only when the AC is turned on

### ISSUE THREAD

**Issue by leandropineda** [mill1000/midea-ac-py#149]
I've noticed that outdoor temperature starts reporting when the AC is on (see `Front Room AC Outdoor temperature`).

![image](https://github.com/mill1000/midea-ac-py/assets/8092356/2d72a4e2-7bba-4ade-8232-f2a02b83e960)

Also, as soon as I turn it off, the Outdoor temperature jumps from 1 to 10 degrees.

![image](https://github.com/mill1000/midea-ac-py/assets/8092356/36a42433-ded0-4373-b572-ce47f412588a)

I just wanted to confirm if this is how the AC works or a limitation on the [msmart](https://github.com/mill1000/midea-msmart) library (which I'm happy to help fixing).

Thanks!

**Comment by mill1000** [comment]
This feels like it's going to be a quirk of the AC unit, but lets find out for sure.

Can you enable debug logging and switch the device from on to off? You'll want to wait about 30 seconds before making any chances to be sure the necessary messages are logged.

**Comment by KVinS** [comment]
> This feels like it's going to be a quirk of the AC unit, but lets find out for sure.
> 
> Can you enable debug logging and switch the device from on to off? You'll want to wait about 30 seconds before making any chances to be sure the necessary messages are logged.

I have the same situation. I tried to make a debug log. Hope this helps you.

[home-assistant_midea_ac_2024-06-29T16-10-53.411Z.log](https://github.com/user-attachments/files/16041397/home-assistant_midea_ac_2024-06-29T16-10-53.411Z.log)

**Comment by mill1000** [comment]
Thanks. In this log it does look like the device stops reporting outdoor temperature when the unit is off.

So this might just be a device quirk.

**Comment by KVinS** [comment]
> Thanks. In this log it does look like the device stops reporting outdoor temperature when the unit is off.
> 
> So this might just be a device quirk.

It's a pity. Apparently you'll have to add an external temperature sensor.

**Comment by leandropineda** [comment]
These are my logs: 
[ac_logs2.txt](https://github.com/user-attachments/files/16059501/ac_logs2.txt)

Same issue as before.
![image](https://github.com/mill1000/midea-ac-py/assets/8092356/3538c8c5-a9b9-4cc4-98a1-467c0a0e8f0d)

**Comment by mill1000** [comment]
Yep, looks like the same behavior. The device actually stops sending outdoor temperature data when it's off.

**Comment by mill1000** [comment]
Closing this as there's nothing I can do.
