### ISSUE TITLE
Missing action for automation 

### ISSUE THREAD

**Issue by drgteye** [mill1000/midea-ac-py#151]
First off, I'm very new to HA, and I'm not sure if this warrants an issue request.

I have a Midea 12k U shaped window AC (Model - MAW12AV1QWT-C) and just about everything works as expected in HA.

The one issue I'm having is when I set up an automation.  I'd like to be able to change the temperature on the Midea AC, however my only available actions are:
Fan speed value
HVAC mode
Preset mode
Display on/off/toggle
Purifier on/off/toggle

On my dashboard I have added a thermostat card for this AC, and I'm able to change the temperature there.

Am I missing something, or is there a missing "action" for this device/integration?

TIA

**Comment by mill1000** [comment]
When adding your automation action you should select "Climate" instead of "Device" and then you should see a "Set target temperature" option.

**Comment by drgteye** [comment]
Thank you so much!!!

**Comment by drgteye** [comment]
Thank you so much

**Comment by mill1000** [comment]
No problem!
