### ISSUE TITLE
Errors in log: failed CRC and checksum

### ISSUE THREAD

**Issue by KVinS** [mill1000/midea-ac-py#153]
Home Assistant Core: 2024.6.2
Midea Smart AC: 2024.5.5

Hello. I see this error in the log, although everything seems to be working fine:

```
Payload 'c00129657f7f000008400163610d70660001310000000004580200000000' failed CRC and checksum. Received: 0x0, Expected: 0x2C or 0x33.
Payload 'c00029657f7f000000000063ff0d00070000000000000004580200000000' failed CRC and checksum. Received: 0x0, Expected: 0x5A or 0xE0.
Payload 'c00029657f7f000000000063ff0d00080000000000000004580200000000' failed CRC and checksum. Received: 0x0, Expected: 0xE7 or 0xDF.
Payload 'c00048667f7f000000000067ff0c00060000000000000004580200000000' failed CRC and checksum. Received: 0x0, Expected: 0x12 or 0xBE.
```

**Comment by mill1000** [comment]
Hi. Haven't seen that one in a while. 

Can you enable debug logging and post the full logs after a few minutes of running?

**Comment by KVinS** [comment]
> Hi. Haven't seen that one in a while.
> 
> Can you enable debug logging and post the full logs after a few minutes of running?

I just attached the log of the air conditioner in another issue :D

**Comment by mill1000** [comment]
Ah you did! Thanks. :D

I'm on a trip so I'll look at this in a few days.

**Comment by KVinS** [comment]
> Ah you did! Thanks. :D
> 
> I'm on a trip so I'll look at this in a few days.

Check also the new localization file

**Comment by mill1000** [comment]
OK so the odd thing is the CRC/Checksum errors are not for every response. 

In this [log](https://github.com/mill1000/midea-ac-py/issues/149#issuecomment-2198247696) the errors also occur periodically about once per minute. They also for the most part have the same payload `c00048667f7f000000000067ff0c00060000000000000004580200000000`

**Comment by mill1000** [comment]
An interesting test might be to set the maximum connection lifetime to a value like 45 seconds. I wonder if regularly recreating the connection will prevent these errors.

**Comment by KVinS** [comment]
> An interesting test might be to set the maximum connection lifetime to a value like 45 seconds. I wonder if regularly recreating the connection will prevent these errors.

Something new...
```
Unknown capability. ID: 0x0040, Size: 1.
Unsupported capability. ID: 0x0051, Size: 1.
Unsupported capability. ID: 0x0048, Size: 1.
Unsupported capability. ID: 0x0067, Size: 1.
```
[home-assistant_midea_ac_2024-07-01T20-40-06.572Z.log](https://github.com/user-attachments/files/16058896/home-assistant_midea_ac_2024-07-01T20-40-06.572Z.log)

**Comment by mill1000** [comment]
Latest log has far less CRC errors. Setting that lifetime may be the trick to suppress those.

Those warnings are nothing to worry about. Your device just has some functionality I haven't implemented support for.

**Comment by KVinS** [comment]
> Latest log has far less CRC errors. Setting that lifetime may be the trick to suppress those.
> 
> Those warnings are nothing to worry about. Your device just has some functionality I haven't implemented support for.

I wonder which ones? It seems like everything is there...

Midea MSFE-09N8D6-I/MSFE-09N8D6-O

**Comment by mill1000** [comment]
| Unknown capability. ID: 0x0040, Size: 1.

This one is a mystery. Seen it in a number of logs but I can't find any references to it.

| Unsupported capability. ID: 0x0051, Size: 1.

This appears to be some form of parental control.

| Unsupported capability. ID: 0x0048, Size: 1.

This is rate select or what is also called "Gear"

| Unsupported capability. ID: 0x0067, Size: 1.

This is something called Jet Cool

**Comment by mill1000** [comment]
Oh, and doesn't necessary mean your device supports them. It could be including those IDs just to explicitly state that it **doesn't** support them.

**Comment by KVinS** [comment]
> Oh, and doesn't necessary mean your device supports them. It could be including those IDs just to explicitly state that it **doesn't** support them.

There was something in the instructions about parental controls.
Is there any way I can help you analyze this?

**Comment by KVinS** [comment]
By the way, wouldn’t it be more logical to move the beep enabled to the display panel?

**Comment by mill1000** [comment]
Appreciate the offer for help.

Parental controls isn't a high priority for me to implement. There has been some interest in the Gear function (#60 #161).

Closing this issue now as it seems the original issue has been resolved.
