### ISSUE TITLE
hvac actions supported?

### ISSUE THREAD

**Issue by ChristophCaina** [mill1000/midea-ac-py#157]
Hi,
I'm new to the integration and using it for less than two days now... so sorry, if this is already known or expected...

First - the integration of my AC works well - it is a Comfee Eco Cool Pro 2.9
But when I set the AC to cool, and it powers on, the Thermostat does not show, that the device is cooling.
Is this feature (hvac action) not supported?

![image](https://github.com/mill1000/midea-ac-py/assets/26391061/d632f60c-c3c6-4178-8c9a-d94c489a8b56)

compared to a heating Device:
![image](https://github.com/mill1000/midea-ac-py/assets/26391061/23c2d920-3c4c-43b4-bb22-3e06164c3d1e)

**Comment by mill1000** [comment]
Hi.

Unfortunately no this integration does not support `hvac_action`. The device doesn't provide any information about it's current state (e.g. idle, cooling, heating).

**Comment by ChristophCaina** [comment]
OK, thank you.
