### ISSUE TITLE
Remove "Filter alert" from Diagnostics

### ISSUE THREAD

**Issue by ChristophCaina** [mill1000/midea-ac-py#175]
I would recommend to remove the Binary Sensor "Filer alert" from the 'Diagnostic' section and move it to the Sensors Section of the Device.

![image](https://github.com/user-attachments/assets/62b9026e-2433-44b7-81b3-0624191ca682)

This would allow the user to use this sensor information also as Alert_Class on the Area Card, like in this example:
![image](https://github.com/user-attachments/assets/d3129327-3a66-4d85-bdc8-887cbf2b88ee)

Whenever the Sensor will be on, an Icon would then be shown on the AreaCard to make the user aware of an issue:
![image](https://github.com/user-attachments/assets/5ff790e7-9cb9-4401-b611-b030f90f3fb8)

Unfortunately, this is only possible, when a Sensor is NOT within the Diagnostics Entity_Category.

**Comment by mill1000** [comment]
Thanks for the tip. Easy enough to change

Looks like you're active in this issue on the frontend: https://github.com/home-assistant/frontend/issues/19951

**Comment by ChristophCaina** [comment]
Yes :)
Personally, i think this should be changed in ha to include Diagnostic Sensors... But changing it here IS probably faster ^^
