### ISSUE TITLE
Manually add device

### ISSUE THREAD

**Issue by Hadatko** [mill1000/midea-ac-py#19]
Hi, can i somehow manually add device without gui? HA is behind proxy and gui shows (i want fix this error but meantime i would like to try your integration ;)):
![image](https://github.com/mill1000/midea-ac-py/assets/13130700/f982ea56-c4b6-42b8-b41d-ce548cfe8535)

**Comment by Hadatko** [comment]
Nevermind. I remembered that i need just comment some lines in HA configuration

**Comment by mill1000** [comment]
Well let me know if any other issues pop up.
