### ISSUE TITLE
Energy consumption report

### ISSUE THREAD

**Issue by v1k70rk4** [mill1000/midea-ac-py#194]
Hi,

I think the Realtime Power (power) value is displayed incorrectly. 

Even though it doesn't correspond to reality according to what Midea calculates :), the value shown by the integration is definitely incorrect.

Based on the values from the official application and another integration, a division by 1000 will be necessary.

Smart AC:
![image](https://github.com/user-attachments/assets/489caf71-b380-42a5-8a33-797b3c1fa15c)

Midea AC:
![image](https://github.com/user-attachments/assets/57e1ef03-b5e0-4c16-a229-51d2daaa85c5)

**Comment by mill1000** [comment]
Thanks for the feedback. Very helpful.

Otherwise, it looks like the total and current energy consumption values are OK?

**Comment by mill1000** [comment]
Could you snag debug logs too?

**Comment by v1k70rk4** [comment]
Hi,

the other values are the same as what the other integration says, but when I look at the graph, there is a difference.

I'll show you a picture that, in my opinion, doesn't relate to reality (Sometimes the TOTAL decreases :) ). But I don't think it's the fault of your integration. I think the Chinese either try to show how energy-efficient it is this way, or they calculate something from this data in some twisted manner. The app shows these values, but it doesn't fluctuate; it's as if they update it once a day and accumulate a value from this data.

The problem is that all my air conditioners are built-in, and I can't install a consumption meter on them. :(
Plus, only the breezeless model can measure consumption, which is at my parents' house. My air conditioners at home can't do this.

SmartAC:
![image](https://github.com/user-attachments/assets/3d07ed34-a411-4a74-aaad-154bab7122ca)

MideaAC-LAN:
![image](https://github.com/user-attachments/assets/ff73565a-05b8-41da-b5e8-0ba3a3c9f8f4)


and the requested debug log, if you need a longer one just let me know and I'll make it :)
[midea.240723_2024.log](https://github.com/user-attachments/files/16353148/midea.240723_2024.log)

**Comment by mill1000** [comment]
Thanks. The midea_ac_lan integration seems to be getting much more data. I thought we were using the same message, but it clearly is getting additional data from somewhere.

**Comment by mill1000** [comment]
Hm...ok so these logs are reporting your real time power to be about 120, which is probably in Watts.

Quick fix.
