### ISSUE TITLE
Unable to add device after instalation from HACS

### ISSUE THREAD

**Issue by tomiko23lol** [mill1000/midea-ac-py#195]
Hi I installed Midea Smart AC by HACS link. After restart of Homeassistant I was not able to see in **Settings / Devices & Services / Devices / + ADD DEVICE** Midea Smart AC

This thing "Midea Smart AC" was missing:
![image](https://github.com/user-attachments/assets/59dd17aa-80cb-4ab9-94fb-8bc1d740da21)

I than went trough manual installation process by creating and copying files in to custom_components/midea_ac 

![image](https://github.com/user-attachments/assets/7f0ae38e-b683-48f2-bc30-689b67ba5c2d)

After next restart, I could see device type when adding new Midea AC and it started working as expected.

I am not sure if I understood installation manual wrong or something, but to me it sounds like I have two options
A) You can install it from HACS and all will work, no manual work needed
B) install it manually by copying of those files and folders

In my case I was forced to do both, so please either check and repair HACS installation process or change manual so it is more clear that it is two step process and not 2 different options.
Also it would be nice to include screenshot of actual adding of new device instead of just adding this generic link https://www.home-assistant.io/getting-started/integration/ ( for novice users at least, I was not sure whether I am looking on the right place or that integration should appear somewhere else )

Thank You :)

**Comment by mill1000** [comment]
Hi there. Sorry you had some trouble.

It is only necessary to perform one of the installation methods. It should not be necessary to do both.

I just tried installing via HACS and had no issues after a reboot. Perhaps the browser cache needed a refresh?

I'll update the README with a more specific screenshot. Thanks for the recommendation

**Comment by mill1000** [comment]
README has been updated with screenshot.
