### ISSUE TITLE
ECO mode preset should only be visible when Cooling mode is active

### ISSUE THREAD

**Issue by paradox37** [mill1000/midea-ac-py#2]
**Describe the bug （描述一下问题）**
ECO mode preset should only be visible when Cooling mode is active since that preset can only be activated for that mode. 

**Versions (版本信息)**
 - Home Assistant version: Latest
 - Midea msmart version: future branch

**Comment by mill1000** [comment]
Does the manual for your device specify if ECO works in any other modes? My manual says it should work in COOL, AUTO and DRY.

**Comment by paradox37** [comment]
Well, funny thing is, manual does not mention ECO for my AC at all. I can only use this option from NetHome. And it only works with Cool mode. I tried Dry and Auto, but NetHome says I can not use it in those modes.

**Comment by mill1000** [comment]
Interesting. Perhaps ECO preset should just not be available in Heating mode.
