### ISSUE TITLE
Power, current and energy sensors not available

### ISSUE THREAD

**Issue by vinceg0267** [mill1000/midea-ac-py#201]
Hi,
in my integration, version 2024.7.10, Power, current and energy sensors are not available.

Also I don't know how to install msmart-ng, can anyone help me?

![Screenshot (17)](https://github.com/user-attachments/assets/b436b3ec-49b9-4db4-8e20-a4adb304b236)

**Comment by v1k70rk4** [comment]
Hi, not many air conditioners can measure this value. What type of air conditioner do you have? Do you see these values in its application? 
msmart-ng appropriate version installs itself ;)

**Comment by zhaqianyuan** [comment]
I have the same problem. I use HAHIN(Hualing) N8HL1Pro. and it have total energy in app.

**Comment by mill1000** [comment]
@zhaqianyuan can you provide logs with debugging enabled?

**Comment by vinceg0267** [comment]
> Hi, not many air conditioners can measure this value. What type of air conditioner do you have? Do you see these values in its application? msmart-ng appropriate version installs itself ;)

I have a Midea Extreme series air conditioner. In the App I do not see these values, but with the Midea AC Lan integration I have the real time power sensor, but always 0, and the current and total energy sensors but I can not understand the meaning.
![Screenshot 2024-07-29 at 06-08-44 Impostazioni – Home Assistant](https://github.com/user-attachments/assets/14f9d77d-bb86-4e9d-a5c7-c6278e94845f)

![Screenshot 2024-07-29 at 06-17-33 Impostazioni – Home Assistant](https://github.com/user-attachments/assets/bda8ffd6-1be0-45a7-9413-a4de7acc29a4)

![Screenshot 2024-07-29 at 06-18-23 Impostazioni – Home Assistant](https://github.com/user-attachments/assets/64d9454a-fa71-4c06-9b3f-20408208ec55)

**Comment by zhaqianyuan** [comment]
> @zhaqianyuan can you provide logs with debugging enabled?

[home-assistant_midea_ac_2024-07-29T08-37-47.463Z.log](https://github.com/user-attachments/files/16409940/home-assistant_midea_ac_2024-07-29T08-37-47.463Z.log)

**Comment by mill1000** [comment]
@zhaqianyuan Thanks. The device is reporting total energy usage in this log. And nothing shows up in HA? Did you wait the 30 seconds or so after enabling the sensors for the integration to reload? Have you tried restarting HA?

@vinceg0267 Ok, can you provide logs with debugging too?

**Comment by mill1000** [comment]
Also as a rule of thumb. Never run this integration while running `midea_ac_lan`. In my experience the AC device does not respond well if too many other devices are querying it.

**Comment by zhaqianyuan** [comment]
@mill1000 I tried, but it still doesn't work

**Comment by mill1000** [comment]
Hm...this makes no sense to me.

What version of HA are you running? I might need you to run a custom branch to debug this one.

I hacked up a testbench that uses the data from your logs and it works on my system.
![image](https://github.com/user-attachments/assets/e0a6ba98-a4d8-4648-9e87-2a043487a882)

**Comment by zhaqianyuan** [comment]
@mill1000 HA is Core:2024.7.2 Frontend:20240710.0

**Comment by zhaqianyuan** [comment]
> Hm...this makes no sense to me.
> 
> What version of HA are you running? I might need you to run a custom branch to debug this one.
> 
> I hacked up a testbench that uses the data from your logs and it works on my system.
> ![image](https://github.com/user-attachments/assets/e0a6ba98-a4d8-4648-9e87-2a043487a882)
> 

the value of energy in app![S40729-16430458.png](https://github.com/user-attachments/assets/7158da37-0019-405a-b168-ab3189e6c105)

**Comment by vinceg0267** [comment]
> @vinceg0267 Ok, can you provide logs with debugging too?
[midea debug log.txt](https://github.com/user-attachments/files/16422112/midea.debug.log.txt)

**Comment by mill1000** [comment]
Thanks to both of you. I think I've located the issue.

**Comment by mill1000** [comment]
Latest release should have this fixed. Please re-open if it still doesn't work.

**Comment by vinceg0267** [comment]
I added the lines of code manually, the sensors are now available. The Power sensor however returns 0 Kw.
Also, can you explain the difference between the Current and Total Energy sensor? Both are in kWh.

**Comment by mill1000** [comment]
> The Power sensor however returns 0 Kw.

As said before, not all devices support all fields.

> Also, can you explain the difference between the Current and Total Energy sensor? Both are in kWh.

As best I can tell. Total energy is the total energy used by the device over its lifetime. Current energy is the energy used in the current "run". What constitutes a "run" is unclear to me. Perhaps when it's turned on.
