### ISSUE TITLE
Discrepancy between integration Power and Midea app power

### ISSUE THREAD

**Issue by sltelitsyn** [mill1000/midea-ac-py#204]
Hi.

I've found a discrepancy between AC power consumption in the Midea app and HA Integration:
![IMG_0501](https://github.com/user-attachments/assets/a9d9423f-2cd8-4a7e-80c3-41f3f5373697)
![IMG_0500](https://github.com/user-attachments/assets/3d7799d3-72a1-4d1d-8b6f-bfc5777b1032)

Overall home power consumption sensor shows that the app is correct.

**Comment by mill1000** [comment]
Probably due to https://github.com/mill1000/midea-msmart/issues/154

**Comment by mill1000** [comment]
Can you provide debug logs for your device?

**Comment by sltelitsyn** [comment]
Here they are:
[MideaDebugLogs.zip](https://github.com/user-attachments/files/16447273/MideaDebugLogs.zip)

**Comment by mill1000** [comment]
Thanks. Yeah looks like this is the same.

The alternate decode puts the power at approx. 249 W

**Comment by sltelitsyn** [comment]
This is closer to be true, yes

**Comment by mill1000** [comment]
Ok thanks. I haven't decided how I want to handle this yet.

I don't know if anyone has confirmed the current power number as valid yet on their device.

**Comment by LeSpocky** [comment]
Using a Midea PortaSplit here.

I can confirm power and energy I see in HomeAssistant are 1. different to values in the *SmartHome* app and 2. different to values measured by a Shelly PlusPlugS.

Even worse: the energy curves in HomeAssistant jump backwards which makes them completely useless in the HA Energy Dashboard.

![Screenshot_20240822_152239](https://github.com/user-attachments/assets/fbb47bb6-f6b4-48f4-873c-307f7108c12c)

**Comment by mill1000** [comment]
> Even worse: the energy curves in HomeAssistant jump backwards which makes them completely useless in the HA Energy Dashboard.

This could be due to improper parsing of the data.

Can you provide debug logs from your device along with a snapshot of the energy usages from the SmartHome app and/or Shelly.

**Comment by LeSpocky** [comment]
> > Even worse: the energy curves in HomeAssistant jump backwards which makes them completely useless in the HA Energy Dashboard.
> 
> This could be due to improper parsing of the data.
> 
> Can you provide debug logs from your device along with a snapshot of the energy usages from the SmartHome app and/or Shelly.

Here you go, hope that helps: [midea (1).zip](https://github.com/user-attachments/files/16728342/midea.1.zip)

**Comment by mill1000** [comment]
Thanks. Here's two possible interpretations

Existing BCD decoding
```
BCD Energy Total 4.31, Current 0.33, Power 97.5
```

Binary decoding
```
Bin Energy Total 971, Current 51, Power 2415
```

Power should be divided by 10 to get Watts.


It would be really interesting to get a debug log when the total energy jump backwards.

**Comment by LeSpocky** [comment]
> It would be really interesting to get a debug log when the total energy jump backwards.

There are two types of backward jumps.  

First happens roughly every hour if the device is on, looks like small sawtooths in the graph, jumping back around 0.05 kWh each time.

Second type is that big jump, which does happen roughly once a day, jumping back around 0.65 kWh.  I attach the debug log and screenshot from yesterday including such a jump between 14:15 and 14:25 (CEST).  Note: The total value is also wrong.  While in HA it is at 6.46 kWh it is at 12.07 kWh in the SmartHome app.

Hope you find it in the logs, quite big this time.

[2024-08-27.zip](https://github.com/user-attachments/files/16780715/2024-08-27.zip)

**Comment by karlbeecken** [comment]
Hi, I am also experiencing this issue. Is there a way to switch over to Binary encoding yet? I installed the `feature/alternate_energy` branch and enabled the alternate energy feature, but the reported energy is still not correct

**Comment by mill1000** [comment]
Branch hasn't been tested yet, so probably just a bug

**Comment by LeSpocky** [comment]
![Screenshot_20240904_122848](https://github.com/user-attachments/assets/e0a777ad-efbe-4660-a88d-01ca1edfc93f)

Power looks good now. 🥳 

Total Energy is still wrong, and current energy probably wrong too.  Shall we create a new ticket for that?

**Comment by karlbeecken** [comment]
Power also looks good now on my installation, energy seems to be off by factor 10 (A/C was running for an hour with ~320 W power, but reports 3.2 kWh for this period)

**Comment by mill1000** [comment]
> Total Energy is still wrong, and current energy probably wrong too. Shall we create a new ticket for that?

Sure lets track that separately. What does the energy look like now and what do you expect instead?

**Comment by trzenaro** [comment]
Thanks for the fix @mill1000 
I was about to open an issue, but I found this fix and it worked perfectly after updating to [2024.9.0](https://github.com/mill1000/midea-ac-py/releases/tag/2024.9.0)
![image](https://github.com/user-attachments/assets/578a649d-a67f-4168-b5b5-e3eb1cac8649)

![image](https://github.com/user-attachments/assets/cadffb38-e7a1-4ae8-859a-b362476cfc69)

![image](https://github.com/user-attachments/assets/aaf1ab7e-f37e-4b5f-9cc0-a425d64824f6)

**Comment by RoganDawes** [comment]
Recognising that this issue is closed, and even the "Alternate Energy Format" option now has A and B options, which I don't see referenced in other issues, I still wanted to try and resolve the discrepancy I am seeing in my Midea Breezeless split air conditioner.

<img width="360" alt="Image" src="https://github.com/user-attachments/assets/f05f47d4-f8fd-4ff8-b8e7-c2ef491e5d71" />

The image shows the power reported by the Midea integration (in blue) and the reports from a calibrated smart plug. Initially, the Midea power figures are reported using the Default interpretation, and are between 1/3 and 1/4 of those reported by the smart plug. The sharp jump occurs when I switch to Alternate A, and the gap occurs when I switch to Alternate B, because it causes the integration to fail to set up the device, and appears to crash the integration to the point that while I can set the option back to Alternate A, it will not recover without a reboot.

```
2025-02-03 11:55:49.332 ERROR (MainThread) [msmart.device.AC.device] Payload 'a30a00000000000000000000000000' failed CRC and checksum. Received: 0x0, Expected: 0x44 o
r 0x53.
2025-02-03 11:55:49.332 ERROR (MainThread) [msmart.device.AC.device] Payload 'a30a00000000000000000000000000' failed CRC and checksum. Received: 0x0, Expected: 0x44 o
r 0x53.
2025-02-03 11:55:49.332 ERROR (MainThread) [msmart.device.AC.device] Payload 'a30a00000000000000000000000000' failed CRC and checksum. Received: 0x0, Expected: 0x44 o
r 0x53.
2025-02-03 11:55:49.332 ERROR (MainThread) [msmart.device.AC.device] Payload 'a30a00000000000000000000000000' failed CRC and checksum. Received: 0x0, Expected: 0x44 o
r 0x53.
2025-02-03 11:55:49.332 ERROR (MainThread) [msmart.device.AC.device] Payload 'a30a00000000000000000000000000' failed CRC and checksum. Received: 0x0, Expected: 0x44 o
r 0x53.
2025-02-03 11:55:49.332 ERROR (MainThread) [msmart.device.AC.device] Payload 'c00157507f7f003f00000063630b00690000000000000004580200000000' failed CRC and checksum. R
eceived: 0x0, Expected: 0xA or 0xC3.
2025-02-03 11:55:49.501 ERROR (MainThread) [msmart.device.AC.device] Payload 'c1210144000056910000000000000000000c58000000' failed CRC and checksum. Received: 0x0, Ex
pected: 0x24 or 0x8E.
2025-02-03 11:55:49.668 ERROR (MainThread) [msmart.device.AC.device] Payload 'c12101453e4d78065700000000001e0200b28b000000' failed CRC and checksum. Received: 0x0, Ex
pected: 0x42 or 0x1B.
2025-02-03 11:56:05.041 ERROR (MainThread) [msmart.device.AC.device] Payload 'a30a00000000000000000000000000' failed CRC and checksum. Received: 0x0, Expected: 0x44 o
r 0x53.
2025-02-03 12:00:15.273 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry midea_ac 151732605830810 for midea_ac
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac/__init__.py", line 71, in async_setup_entry
    await device.get_capabilities()
  File "/usr/local/lib/python3.13/site-packages/msmart/device/AC/device.py", line 421, in get_capabilities
    if response.additional_capabilities:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'additional_capabilities'
```

So, I think there are a couple of issues here:

1. Is it plausible that there is yet another interpretation for these values from the aircon?
2. I guess the loop should be improved such that the exception does not kill the integration and force the reboot.

Thanks for the work on this integration!

**Comment by mill1000** [comment]
> Is it plausible that there is yet another interpretation for these values from the aircon?

Yes it could be. There's a handful of possible ways to decode the data.

> I guess the loop should be improved such that the exception does not kill the integration and force the reboot.

I think you must be encountering another significant issue. The only difference between alternate A and alternate B is a scaling factor.

Can you create a new issue with a full debug log after reboot?

**Comment by RoganDawes** [comment]
Hi, I did try to find documentation explaining how to do the requested debugging, but did not see it. Please explain what debugging you are after, and how I enable it? I presume you would like to see me changing from Alternate A to Alternate B to see if the exception happens again?

**Comment by mill1000** [comment]
Debugging can be enabled from the integration page.

![Image](https://github.com/user-attachments/assets/3c180768-f526-4133-95f7-354391453816)

And yes, after enabling debugging I would like you to restart HA or reload the integration and then try switching to alternate A.

(But also go ahead a create a new issue with this info)
