### ISSUE TITLE
No Current Energy and Power

### ISSUE THREAD

**Issue by desek90** [mill1000/midea-ac-py#207]
Hello,
I'm having issues with Current Energy and Power entity. They don't get updated and always show 0. Is this a common issue? The Total Energy entity seems to to work fine. I started the Debug Mode 3 Minutes after I turned on the AC. The measurement is attached. 
I'm using the Samsung AR35 AR12TXHQASIN in connection with OSK-103 dongle.

Best Regards,
Bart

<img width="337" alt="overview" src="https://github.com/user-attachments/assets/ff85fe9e-0739-416b-9afa-955e59065fab">
<img width="583" alt="TotalEnergy" src="https://github.com/user-attachments/assets/27da075a-5815-41f1-bb6d-ca656b40e62c">
<img width="581" alt="Energy" src="https://github.com/user-attachments/assets/ac4f9a2f-5116-40bc-9a38-cb57987266dc">
<img width="583" alt="Power" src="https://github.com/user-attachments/assets/fde1d37d-61e1-4e38-8a64-deca286a5a1c">

[home-assistant_midea_ac_2024-08-07T10-08-10.893Z.log](https://github.com/user-attachments/files/16521903/home-assistant_midea_ac_2024-08-07T10-08-10.893Z.log)

**Comment by mill1000** [comment]
Your device likely doesn't support current energy or real time power sensor. 

The responses from the device contain all zeros for current energy and real time power.

**Comment by desek90** [comment]
Thank you for your reply. Would it be possible from your site to calculate the power from the total energy counter? It's a division of total energy increase by step duration. In my case it would be around 510W in Dry mode and 2W standby power.

Maybe you could check if the AC has a real power sensor, then you just extract that data. If not, you could use the calculated power.

Best Regards,
Bart

**Comment by mill1000** [comment]
I think that's out of scope of this integration. My goal is to just report data from the AC with as little post-processing as possible.

You could try using a [derivative sensor](https://www.home-assistant.io/integrations/derivative/) or a template sensor to achieve what you've described in HA.
