### ISSUE TITLE
Unable to turn off "breeze" modes on Breezeless device

### ISSUE THREAD

**Issue by lpispek** [mill1000/midea-ac-py#212]
![image](https://github.com/user-attachments/assets/705b1f49-9f78-4220-926b-a89b9b46caae)

The device made 2 beep signals and the mode stayed ON. IP of the Breezeless device is 192.168.254.13.

I am sharing with you the debug log from HA:
[home-assistant_midea_ac_2024-08-10T20-00-44.710Z.log](https://github.com/user-attachments/files/16570757/home-assistant_midea_ac_2024-08-10T20-00-44.710Z.log)

**Comment by mill1000** [comment]
You can't turn off any of them or just breezeless?

**Comment by lpispek** [comment]
On breezless device I can't turn off any mode. For non breezless device the mode "Breeze Away" is working (you can turn it off)

**Comment by Jarrekstar** [comment]
+1, I just noticed the same issue with my Midea Breezeless E devices

**Comment by mill1000** [comment]
Ok. Thanks for the update. I'll look into this

**Comment by mill1000** [comment]
Can you switch between modes? e.g. Breezeless to breeze away?

**Comment by mill1000** [comment]
Tracking this issue in msmart-ng here: https://github.com/mill1000/midea-msmart/issues/161

**Comment by Jarrekstar** [comment]
> Can you switch between modes? e.g. Breezeless to breeze away?

Yes, that works fine

**Comment by lpispek** [comment]
> Can you switch between modes? e.g. Breezeless to breeze away?

Yes, it is possible to change the modes. But on every mode change and mode turning on device has 2 beeps instead of one like is on all other functions.

**Comment by mill1000** [comment]
This should be fixed in 2024.8.1

**Comment by lpispek** [comment]
Thank you for the quick fix.

**Comment by Jarrekstar** [comment]
Thanks for the quick fix! Much appreciated! Sorry for not being able to
test, i barely have time to sit down to my desk these past few days..

**Comment by mill1000** [comment]
No problem. We've all been there

**Comment by lpispek** [comment]
I can confirm that all modes are working.
