### ISSUE TITLE
Setting for LED light

### ISSUE THREAD

**Issue by apella12** [mill1000/midea-ac-py#216]
This is a question because I see you are actively working on this.  Most of the other Midea repositories are old.  

I'm working on a java based Midea binding ("integration") for OpenHab. I was hoping for some friendly advice on the command to turn off the LED light on the indoor unit.  My IR controller does it, but there is no bit changed in the response stream (0xC0) type.  One of the python repositories on github says the set is byte 20 (00010000).  Do you have control of that function? Have you found that some devices do not support it, while others do? I also have the same issue with the clean (IR works, but no bit change while on)

**Comment by mill1000** [comment]
> I'm working on a java based Midea binding ("integration") for OpenHab. 

You may want to checkout the underlying library [msmart-ng](https://github.com/mill1000/midea-msmart). That's what implements the actual control protocol. 

> I was hoping for some friendly advice on the command to turn off the LED light on the indoor unit. My IR controller does it, but there is no bit changed in the response stream (0xC0) type. One of the python repositories on github says the set is byte 20 (00010000). Do you have control of that function? Have you found that some devices do not support it, while others do? I also have the same issue with the clean (IR works, but no bit change while on)

Yes I do have control of the LED display for certain devices. Unfortunately certain devices appear to only have LED control via IR and do not expose the setting via the network.

**Comment by apella12** [comment]
Thanks !
