### ISSUE TITLE
False current energy

### ISSUE THREAD

**Issue by dannju94** [mill1000/midea-ac-py#217]
Hello, I have a problem. 
It displays an incorrect value. 
Anyone have any ideas ? 

I am using the latest version. 

![IMG_6825](https://github.com/user-attachments/assets/f386c1db-b197-481e-8b86-702e051bf03a)
![IMG_6822](https://github.com/user-attachments/assets/29c575a3-ba73-4e78-ab96-2b1f1b812f35)

**Comment by mill1000** [comment]
Duplicate of #204 and also https://github.com/mill1000/midea-msmart/issues/154

Please provide debug logs of the discrepancy in #204.
