### ISSUE TITLE
Depreciated errors in HA logbook

### ISSUE THREAD

**Issue by Dzoker2** [mill1000/midea-ac-py#223]
Hi,

I noticed few errors in the logbook:

Logger: msmart.device.AC.device
Source: custom_components/midea_ac/climate.py:441
- 'sleep_mode' is deprecated. Please use 'sleep' instead.

Logger: msmart.device.AC.device
Source: custom_components/midea_ac/climate.py:439
- 'freeze_protection_mode' is deprecated. Please use 'freeze_protection' instead.

Logger: msmart.device.AC.device
Source: custom_components/midea_ac/climate.py:437
- 'turbo_mode' is deprecated. Please use 'turbo' instead.

Logger: msmart.device.AC.device
Source: custom_components/midea_ac/climate.py:435
- 'eco_mode' is deprecated. Please use 'eco' instead.

Do I need to do anything to remedy this?

Thank you

**Comment by mill1000** [comment]
You must have pulled the latest `msmart-ng` before the integration has been updated.

It'll be fixed soon enough.
