### ISSUE TITLE
Alternate Energy Format: Values much too high

### ISSUE THREAD

**Issue by LeSpocky** [mill1000/midea-ac-py#230]
Using a Midea PortaSplit here, ticked the box for "Alternate Energy Format" in device settings.

While #204 was fixed in release 2024.09.0 for power, the energy reading seems to be wrong.  The value is expected to be smaller by (roughly?) factor 10.  Integrating over Midea power values gives the same energy as measured by a Shelly Plug, so power seems to be correct.  Attaching some screenshots from today: [2024-09-04.zip](https://github.com/user-attachments/files/16880886/2024-09-04.zip).

**Comment by LeSpocky** [comment]
![Screenshot_20240904_122421.png](https://github.com/user-attachments/assets/b79b4516-7e04-46fd-ad37-5f57f63e58df)

The long cyan bar on top is the wrong value from the integration. The three bars of same length below have the right values, those are reported Energy from Shelly Plug, and energy calculated by integration over Power (shelly and midea integration).

**Comment by Wurmi1986** [comment]
Hi, I have a similar problem. If I don't use the “Use Alternate Energy Format” mode, the values in the HA are much too low. The Midea app and also my Shelly Plug S show significantly higher values. If I check the box next to “Use Alternate Energy Format
”, the current values are correct, but “total energy” is then much too high 88 instead of 3.78 kWh
![image](https://github.com/user-attachments/assets/a745762d-acff-4ac5-8646-52aa3201c155)

![image](https://github.com/user-attachments/assets/9baccfc8-4dc4-4820-b367-81a2dc01f349)
Shelly App:
![image](https://github.com/user-attachments/assets/12c9ff11-0016-43e0-a016-95a82b8e3389)
Midea App:
![image](https://github.com/user-attachments/assets/a2da6df1-cf07-415f-9083-78fcf271ae0c)

**Comment by mill1000** [comment]
@Wurmi1986 So for your unit it appears you need the "alternate" format for power, but the "original" format for energy?

**Comment by LeSpocky** [comment]
> Or is total energy just off by a factor of 10? e.g. It should be 8,88 kWh instead of 88,8 kWh?

His SmartHome App Screenshot says 8.73 kWh for the current month. If that's equal to total, then it would be new format with factor 10.

**Comment by karlbeecken** [comment]
Factor 10 doesn't seem to be exactly right, but maybe good enough. The daily usage is always lagging a bit behind in the app, so the difference between 3.1 kWh in HA and 0.28 kWh in the app could be explained by that. The all-time power is also not excatly off by factor 10, but I don't know how often this is updated in the app.

![Screenshot 2024-09-07 at 13-50-53 Settings – Home Assistant](https://github.com/user-attachments/assets/b3550e08-499d-4493-89a9-9918257743e7)
![IMG_2327](https://github.com/user-attachments/assets/a07f3488-60c8-48e7-aa00-cd9e28eaa7b3)
![IMG_2328](https://github.com/user-attachments/assets/c00b6c6c-03b2-480c-8487-d14fb7dfe49a)

**Comment by Wurmi1986** [comment]
Some Screenshots from "total Energy used" 

Midea App:
![WhatsApp Bild 2024-09-09 um 01 08 19_a033d400](https://github.com/user-attachments/assets/164ee49a-2ffa-4bd6-957f-bf013e40e16e)
Shelly App:
![WhatsApp Bild 2024-09-09 um 01 08 53_6bdf0571](https://github.com/user-attachments/assets/fcbb28e0-491e-4ea5-a0f5-91f0e06ab8d3)
Home Assistant:
![image](https://github.com/user-attachments/assets/45b5ddea-f95c-49ee-9d83-4582b3488977)

iam using a Midea PortaSplit if this is important.

best regards
Wurmi

**Comment by Wurmi1986** [comment]
if i uncheck the "Use Alternate Energy Format" it´s not correct either.
![image](https://github.com/user-attachments/assets/0feeb4ca-9c7d-444e-bc1f-e1a817e8ef69)

**Comment by mill1000** [comment]
Alright I can't really find any references for the extra power of 10 but we'll give it a shot

**Comment by mill1000** [comment]
Just a thought, would any of you be willing to run `msmart-ng download` against your device and email me the resulting files?

**Comment by Wurmi1986** [comment]
Hi, i will send u the files later when I am on the computer.Best regardsWurmiGesendet von Outlook für AndroidVon: Tucker Kern ***@***.***>Gesendet: Freitag, September 13, 2024 5:41:22 PMAn: mill1000/midea-ac-py ***@***.***>Cc: Wurmi ***@***.***>; Mention ***@***.***>Betreff: Re: [mill1000/midea-ac-py] Alternate Energy Format: Values much too high (Issue #230)
Just a thought, would any of you be willing to run msmart-ng download against your device and email me the resulting files?

**Comment by LeSpocky** [comment]
> Just a thought, would any of you be willing to run `msmart-ng download` against your device and email me the resulting files?

With a little more instructions where to get this msmart-ng and *how* to run it against my device, sure.

**Comment by mill1000** [comment]
A little info here: https://github.com/mill1000/midea-msmart?tab=readme-ov-file#installing

The command would simply be
`msmart-ng download <IP_OF_DEVICE>`

**Comment by Wurmi1986** [comment]
sorry im am new to git, where can i find your email, can u send it to me?

**Comment by mill1000** [comment]
You can email me at tuckkern@gmail.com

@LeSpocky I got your email. Thank you. The files you sent appear to be the same as the ones I already had access to. Alas, no new information to gleam from them.

**Comment by Coeos3** [comment]
Hi,
I also have issues with the energy values. FYI, I have a Breezeless AC. The alternate method gives much too high values, and the normal method increases, then drops a little, and sometimes drops a lot. Sometimes the drops are so big that I get a negative energy consumption on a day. They are also significantly lower (at least 25%) than what is displayed in the Midea Smart Home app.

<img width="869" alt="image" src="https://github.com/user-attachments/assets/6f23bdbc-9bfd-47c5-9c40-b89398b58935">

The current_energy has the same flaw. 
The real-time power draw also seems a little too low.

I have just started trialling another midea ac integration for the energy related values, and they don't seem to have flaw insofar as it offers 3 energy calculation modes, and the third mode seems to be the right one for my AC ([georgezhao2010/midea_ac_lan ](https://github.com/georgezhao2010/midea_ac_lan/blob/7c5231ca0588d364aa30e3bb2b887b37d4359719/custom_components/midea_ac_lan/midea/devices/ac/message.py#L515) )

Would it be possible to add that third calculation method to this integration?

**Comment by mill1000** [comment]
Hopefully the latest release will resolve this issue for everyone.

**Comment by Wurmi1986** [comment]
Now it matches with the App and with my Shelly. Thanks a lot \m/
