### ISSUE TITLE
One of my 4 units becoming unavailable since version 9.0

### ISSUE THREAD

**Issue by deezid** [mill1000/midea-ac-py#231]
I have 4 units in the house which worked perfectly fine until the 2024.9 release of midea-ac-py but since the update one of these constantly becomes unavailable
<img width="1488" alt="Screenshot 2024-09-05 at 11 56 27" src="https://github.com/user-attachments/assets/22a906a9-5db5-424b-acb3-91bf9e454f27">
[midea log.txt](https://github.com/user-attachments/files/16886771/midea.log.txt)

**Comment by mill1000** [comment]
Sorry you're having trouble.

The log you've provided is not a debug log. I need full debug logs to assist you.

**Comment by mill1000** [comment]
Closing as stale. Feel free to re-open as needed.
