### ISSUE TITLE
ACs disconnecting from WiFi.

### ISSUE THREAD

**Issue by tomiko23lol** [mill1000/midea-ac-py#232]
Hi, I have problem with AC-wifi modules disconnecting / freezing after period of time. 
This started happening after I added Midea-ac-py to my homeasistant. It is happening on all 4 Midea ACs, but usually not on all of them at the same time. In this case **192.168.23.161** is one that got disconnected.

It looks like after some time usually multiple days. it stops responding, in HA it says Unavailable
<img width="777" alt="image" src="https://github.com/user-attachments/assets/17d72bc6-f297-4b74-9583-64360786a163">
On my router I can see that there is no IP registration for this particular MAC address any more ( I have DHCP lease MAC>IP reservations for almost all stuff in my home. ) 

I kept debug logging enable since last restart of AC (2.5 days), I also have Kuma-Uptime setup to ping ACs and it looks like around 17:40 6.Sep.2024 was last successful ping, after that AC stopped responding and lost all connection to network.
<img width="380" alt="image" src="https://github.com/user-attachments/assets/a8e39ea4-06ed-4ecc-8b52-5cf0ba7c70c0">

Here is link for debug log file ( it is too large 350 MB to attach it directly) 
https://drive.google.com/file/d/1Us4LP51LDNy-I2V2S1jFA8oiNCGfF3er/view?usp=sharing

Here You can see that kidsroom AC does not have IP address leased any more for some reason. Screenshot from my Mikrotik
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/9b881489-9b0c-4d04-9c13-ed179c50a47d">

I would appreciate if You could take a look on this issue and help me resolve it. I suspect that it might be some kind of overloading of wifi modules, too frequent polling or something similar. As I say, I never observed this issue when I was using only original midea app. Also this must be only wifi module issue, IR remote control is not affected in any way, so AC itself is OK.

Thx in advance.

**Comment by mill1000** [comment]
Your device appears to disconnect every 2 minutes, possibly leaving some part of the connection hanging. 

You should try setting the Maximum Connection Lifetime setting to a value of 90.

**Comment by tomiko23lol** [comment]
Hi, I have set 90 on all 4 units I have. I will report back whether this helped / repaired issue or not.

Thank You.

**Comment by tomiko23lol** [comment]
Hello, You were right, all units are now set to 90 and those error messages from log disappear and periodic disconnecting and freezing of WiFi modules was solved as well. 
Thank You. :)

**Comment by mill1000** [comment]
Excellent!
