### ISSUE TITLE
How do I know which features are supported?

### ISSUE THREAD

**Issue by parautenbach** [mill1000/midea-ac-py#235]
I just upgraded both HA and this integration to 2024.9.1. 

I had the filter alert entities available before, but now they're unavailable. I'm assuming my ACs don't support this (same with the power sensors, but I already have my own, so that's ok). Was it available by mistake before? 

How would I know what features are available? Is there some place one can check? I suppose I can grab a debug log and decipher the flags, but I was wondering if there's an easier way.

**Comment by mill1000** [comment]
Yes in [2024.7.6](https://github.com/mill1000/midea-ac-py/releases/tag/2024.7.6) I made it so the filter sensor is only displayed if the device claims support for it.

> How would I know what features are available? Is there some place one can check? I suppose I can grab a debug log and decipher the flags, but I was wondering if there's an easier way.

Right now a debug log is the best option. The capabilities will be printed out in plain text, at least you won't have to manually decipher the bits.

I'll consider this a feature request to implement the "diagnostic" platform, where I can expose details of the device.

**Comment by parautenbach** [comment]
> The capabilities will be printed out in plain text, at least you won't have to manually decipher the bits.

Thanks!

> I'll consider this a feature request to implement the "diagnostic" platform, where I can expose details of the device.

That would be awesome.
