### ISSUE TITLE
"Failed to authenticate" recently started on working devices

### ISSUE THREAD

**Issue by KB8DOA** [mill1000/midea-ac-py#240]
We've also just recently had some power outages.
2 of 4 ACs (Toshiba) affected.

How does one verify the IP address (of the AC) that HASS is trying to use to communicate with it?

UPDATE:
The IP addresses have change on these ACs.
I will set them to static - but still need to know where to find the IP Addresses that HASS is expecting to use to communicate with them...

![image](https://github.com/user-attachments/assets/8adfc28a-b504-4bbc-9aa8-6e435d65d604)

**Comment by mill1000** [comment]
If you enable debug logging you should be able to see what IPs are being used.
