### ISSUE TITLE
Preset mode "eco" is not valid. Valid preset modes are: none, sleep.

### ISSUE THREAD

**Issue by hellanerdy** [mill1000/midea-ac-py#242]
Hi. Thanks for using the integration. 
  Before submitting an issue please review the following:
  - Search or browse the existing open and closed issues for your problem. It's likely another user has encountered and resolved the problem. *done*
  - Make sure you are running the latest version of the integration. *done*
  - When creating an issue please include the following:
    - Full logs with debugging enabled. Attach the file or paste logs inside triple backticks.
    - Attach the diagnostic file downloaded from the device page. *just looked, this isn't a thing. not sure why you wasted the text*
    
    *you will get what you get, I'm an electrical engineer, I DO NOT code.*

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:287
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:58:34 PM (4 occurrences)
Last logged: 6:11:38 PM

[547640639552] Preset mode eco is not valid. Valid preset modes are: none, sleep
[547122964960] Preset mode eco is not valid. Valid preset modes are: none, sleep
[547204593792] Preset mode eco is not valid. Valid preset modes are: none, sleep

This error originated from a custom integration.

Logger: msmart.device.AC.device
Source: custom_components/midea_ac/coordinator.py:45
integration: Midea Smart AC (documentation, issues)
First occurred: 5:58:34 PM (17 occurrences)
Last logged: 6:11:37 PM

Device is not capable of eco mode.
Device is not capable of property <PropertyId.IECO: 227>.

**Comment by hellanerdy** [comment]
<!-- READ THIS FIRST:
  Hi. Thanks for using the integration. 
  Before submitting an issue please review the following:
  - Search or browse the existing open and closed issues for your problem. It's likely another user has encountered and resolved the problem. *done*
  - Make sure you are running the latest version of the integration. *done*
  - When creating an issue please include the following:
    - Full logs with debugging enabled. Attach the file or paste logs inside triple backticks.
    - Attach the diagnostic file downloaded from the device page. *just looked, this isn't a thing. not sure why you wasted the text*
    
    *you will get what you get, I'm an electrical engineer, I DO NOT code.*

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:287
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:58:34 PM (4 occurrences)
Last logged: 6:11:38 PM

[547640639552] Preset mode eco is not valid. Valid preset modes are: none, sleep
[547122964960] Preset mode eco is not valid. Valid preset modes are: none, sleep
[547204593792] Preset mode eco is not valid. Valid preset modes are: none, sleep



This error originated from a custom integration.

Logger: msmart.device.AC.device
Source: custom_components/midea_ac/coordinator.py:45
integration: Midea Smart AC (documentation, issues)
First occurred: 5:58:34 PM (17 occurrences)
Last logged: 6:11:37 PM

Device is not capable of eco mode.
Device is not capable of property <PropertyId.IECO: 227>.

**Comment by mill1000** [comment]
> _just looked, this isn't a thing. not sure why you wasted the text_       
> _you will get what you get, I'm an electrical engineer, I DO NOT code._

Hi.

That's a pretty rude attitude from someone asking for help.

Here's the two items I was looking for. At bare minimum I need debug logs to help you.

Enable debug logging, and restart HA or reload the integration.
![image](https://github.com/user-attachments/assets/aaa248f2-5602-4c5a-a774-6fe9f4a4b422)

Diagnostics
![image](https://github.com/user-attachments/assets/9e235386-3653-4fa3-b0b5-acfbe1d2cfde)
