### ISSUE TITLE
Set Midea AC to Eco Mode

### ISSUE THREAD

**Issue by Merril-r** [mill1000/midea-ac-py#252]
Gooday,

How do I set the AC to Eco mode via an automation in HA?

Thanks in advance

**Comment by mill1000** [comment]
If your device supports the ECO preset it's an simple as calling the Climate: Set preset action.

e.g.
![image](https://github.com/user-attachments/assets/2083a6a1-423f-4dd8-a443-747468c34c13)

Or you can use a device action.
![image](https://github.com/user-attachments/assets/f5b5ec04-c572-44c8-b6d8-0a723077a4c4)
