### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by kassabov** [mill1000/midea-ac-py#255]
Hi,
I am trying to add the integration (installed via HACS) and I am getting the error

Config flow could not be loaded: {"message":"Invalid handler specified"}

I am running home assistant 2024.10.3 and the ive4rsion for the integration is 2024.10.1

Is this an issue with the integration or is likely a problem with my installation? Do you have any ideas how to fix that?

Martin

**Comment by kassabov** [comment]
I was able to run the integration after running
pip install msmart-ng
to install the msmart pyhton package

My guess is this dependency is not listed in the integration

**Comment by mill1000** [comment]
Except it very much is.

https://github.com/mill1000/midea-ac-py/blob/main/custom_components%2Fmidea_ac%2Fmanifest.json#L15-L17

Did you restart HA after installing from HACS? Or happen to capture any logs of the failure?

**Comment by kassabov** [comment]
Thanks a lot for the quick response.
The root cause is that I am running home assistant in docker container and the installed python packages does does not persist when the container is recreated (restarts are OK). This could be fixed by building a custom image which contains the package or by mapping persistent volume. I will figure out how to do this.

Bellow are the relevant logs

Martin

-----------------------------
2024-10-20 18:58:45.167 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'midea_ac': Unable to import component: No module named 'msmart'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/midea_ac/__init__.py", line 11, in <module>
    from msmart import __version__ as MSMART_VERISON
ModuleNotFoundError: No module named 'msmart'

**Comment by mill1000** [comment]
> The root cause is that I am running home assistant in docker container and the installed python packages does does not persist when the container is recreated (restarts are OK). This could be fixed by building a custom image which contains the package or by mapping persistent volume. I will figure out how to do this.

Interesting. I run in a container as well and have never had issues with dependencies failing to load when rebuilding or upgrade the container.

**Comment by ross-w** [comment]
I don't know what I'm doing wrong, but I am getting the same issue. I've just switched over to your fork from mac-zhou's.
I've completely removed the old repo from both HACS and custom_components. After installing the new one from HACS and attempting to install the integration, I'm given the same error message as indicated in the first post here.

Initially my log entry was different:
```
Logger: homeassistant.config_entries
Source: config_entries.py:3249
First occurred: 20:45:27 (1 occurrences)
Last logged: 20:45:27

Error occurred loading flow for integration midea_ac: cannot import name '__version__' from 'msmart' (/config/deps/lib/python3.12/site-packages/msmart/__init__.py)
```

But I soon realised this was due to the old `msmart` module persisting in `/config/deps`. After removing this I got the same error as above. No amount of reinstalling this module from HACS and restarting home assistant helped. The only thing that fixed it was to break into the container and run:

```
pip install --target /config/deps/lib/python3.12/site-packages --upgrade --no-deps msmart-ng
```

I'm running a containerised version of HASS 2024.11.1. Note that `/config` is persisted outside the container, so the solution above is permanent, but I do wonder if there is something wrong with the manifest that means this is not getting installed correctly by HACS. Or potentially it is something left over from the old fork on my system...

**Comment by mill1000** [comment]
> But I soon realised this was due to the old msmart module persisting in /config/deps.
> Or potentially it is something left over from the old fork on my system...

Possibly the original `msmart` was also located in your site-packages and maybe that caused a conflict.

>  I do wonder if there is something wrong with the manifest that means this is not getting installed correctly by HACS.

Unlikely as it is validated on every commit by [hassfest](https://github.com/mill1000/midea-ac-py/actions/workflows/hassfest.yml) and the recommended [HAC Actions](https://github.com/mill1000/midea-ac-py/actions/workflows/hacs.yml).

Glad you got it working in the end.
