### ISSUE TITLE
Account or password incorrect

### ISSUE THREAD

**Issue by ztdan4ik** [mill1000/midea-ac-py#256]
Hi
Can't configure device
Using latest version on fresh HA

Logs
Failed to login to cloud. Error: Code: 3102, Message: Account or password incorrect, please re-enter
Could not establish cloud connection.

**Comment by mill1000** [comment]
Thanks for the report. Likely Midea banned the open account we've been using. 

If you have your own account, you can use `msmart-ng` to fetch the token/key and manually configure the device.

**Comment by mill1000** [comment]
Hm.. I re-ran unit tests and the cloud tests passed. Are you still experiencing this issue? Maybe it was an intermittent issue with the Midea servers.

**Comment by ztdan4ik** [comment]
Nope, still having this issue

With msmart-ng I'm getting this

```
INFO:msmart.cli:Discovering all devices on local network.
INFO:msmart.cloud:Using Midea cloud server: https://mp-prod.appsmb.com (China: False).
ERROR:msmart.discover:Failed to login to cloud. Error: Code: 3102, Message: Account or password incorrect, please re-enter
ERROR:msmart.discover:Could not establish cloud connection.
INFO:msmart.cli:Found 1 devices.
INFO:msmart.cli:Found device:
{'ip': '192.168.1.101', 'port': 6444, 'id': 152832116524635, 'online': False, 'supported': False, 'type': <DeviceType.AIR_CONDITIONER: 172>, 'name': 'net_ac_2EC4', 'sn': '000000P0000000Q130B237472EC40000', 'key': None, 'token': None}
```

**Comment by mill1000** [comment]
Thanks for testing. I am able to recreate this in a European codespace.

**Comment by mill1000** [comment]
You can try using your personal account with `msmart-ng`.

e.g.
```
msmart-ng discover -d --account <USER> --password <PASS>
```

**Comment by mill1000** [comment]
```
msmart-ng discover -d --account midea_eu@mailinator.com --password das_ist_passwort1

**Comment by medvjozs** [comment]
Thank you, I was able to do it with my own account as well.

**Comment by ztdan4ik** [comment]
> msmart-ng discover -d --account midea_eu@mailinator.com --password das_ist_passwort1

Thanks
It works for me as well

**Comment by mill1000** [comment]
Ok, thanks for confirming. I'm working on a change here #258 that will allow selecting a region during discovery to use different credentials

**Comment by mill1000** [comment]
Option added in 2024.10.2
