### ISSUE TITLE
Air Conditioning Mundo Clima

### ISSUE THREAD

**Issue by Pinchosct** [mill1000/midea-ac-py#259]
Hello, a few days ago (beginning of this week) that my air conditioner from the brand mundo clima stopped working with this integration, previously it worked, I have updated, it works through the net home app, I have tried previous versions and it no longer works, it detects it automatically but when I add it it says that it cannot be integrated,  I don't know how I can integrate log, please it was going super well so far, would it be possible to help me? If you tell me how to get log I have no problem in providing them, thank you very much in advance.
![nethome](https://github.com/user-attachments/assets/13bef58a-ce48-4a63-ad0e-8a167c936080)
![error](https://github.com/user-attachments/assets/e0fee9a2-2577-4c7f-b024-ddf4f93f2d0e)

**Comment by mill1000** [comment]
Might be related to #256. Please try updating to 2024.10.2 (just released). If that doesn't work, please provide full debug logs and the diagnostic file.

**Comment by Pinchosct** [comment]
> Might be related to #256. Please try updating to 2024.10.2 (just released). If that doesn't work, please provide full debug logs and the diagnostic file.

first of all, thank you for your quick response, I have the latest version of Midea Smart AC, I am going to test the related to the #256 (the little I have been able to test does not give favorable results, tomorrow I will test longer) however... To go ahead... could you tell me how to get the debug logs and diagnostic file? I have never had any problem having to consult this data and I do not know where to obtain it.

**Comment by Pinchosct** [comment]
This is what the command indicated in case #265 throws at me

discover -d --account **MyMail@gmail.com** --password **MyPassword**
DEBUG:asyncio:Using selector: EpollSelector
INFO:msmart.cli:Discovering all devices on local network.
DEBUG:msmart.discover:Discovery sent to 255.255.255.255:6445.
DEBUG:msmart.discover:Discovery sent to 255.255.255.255:20086.
DEBUG:msmart.discover:Waiting 5 seconds for responses...
DEBUG:msmart.discover:Discovery response from **IPDevice**: 837000c8200f00005a5a0111b8007a8000000000d6f63414180a1814421e0200008c0000000000000000018000000000bc6ac0e816bf097530d0d7a28ecad60b6e4d8c8290311b65ddf423722fa7be536d0a6762bf9d5ab28f1e9b2c9a92e6729f27d608d3c05be6ee30132899f47d07b08d22f3be4fbb66909a57da2d089397f3d28b52bb5704abcbab9af7db794cca4bdfb3e16e33d88768cc4c3d0658937d0bb19369bf0317b24d3a4de9e6a131066c2b011fba5d2ee8144df8efc23265fe6f23b371886cb9505aba60a6d5ba7013
DEBUG:msmart.discover:Decrypted data from **IPDevice**: 7f64a8c02c19000030303030303050303030303030305131383037364332333535424338303030300b6e65745f61635f354243380000870002000000000000000000ac00acac000000008076c2355bc8150029102237000301000000000000000000000000000000000000000000000000000000000000000000
INFO:msmart.cloud:Using Midea cloud server: https://mp-prod.appsmb.com (China: False).
INFO:httpx:HTTP Request: POST https://mp-prod.appsmb.com/mas/v5/app/proxy?alias=/v1/user/login/id/get "HTTP/1.1 200 "
DEBUG:msmart.cloud:API response: {"code":"3102","msg":"Account or password incorrect, please re-enter"}
ERROR:msmart.discover:Failed to login to cloud. Error: Code: 3102, Message: Account or password incorrect, please re-enter
ERROR:msmart.discover:Could not establish cloud connection.
DEBUG:msmart.discover:Discovered 1 devices.
INFO:msmart.cli:Found 1 devices.
INFO:msmart.cli:Found device:
{'ip': '**IPDevice**', 'port': 6444, 'id': **IDDevice**, 'online': False, 'supported': False, 'type': <DeviceType.AIR_CONDITIONER: 172>, 'name': 'net_ac_5BC8', 'sn': '**SERIALNUMBERDEVICE**', 'key': None, 'token': None}

**Comment by mill1000** [comment]
> This is what the command indicated in case #265 throws at me

Sorry, I didn't want you to run the commands from that issue.

Make sure you're running 2024.10.2, and try re-adding your device with the Cloud Region changed to country near you.

**Comment by Pinchosct** [comment]
Sorry, I don't understand what you said about the cloud being changed to the nearby country. In the app I have Spain set up.
![Screenshot_20241024_231452_NetHome Plus](https://github.com/user-attachments/assets/4c9c2230-3de3-44bf-acb4-6ecb4c5be2db)
![Screenshot_20241024_231106_Home Assistant](https://github.com/user-attachments/assets/2aff58d7-ef0b-4c2f-a7be-196cc50d519a)

**Comment by mill1000** [comment]
Not in the OEM app, but when setting up the integration like so:
![image](https://github.com/user-attachments/assets/dbdf8754-2a88-442e-876f-316f1faedb33)

**Comment by Pinchosct** [comment]
> Not in the OEM app, but when setting up the integration like so: ![image](https://private-user-images.githubusercontent.com/6924622/379949008-dbdf8754-2a88-442e-876f-316f1faedb33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzY3MzAsIm5iZiI6MTcyOTgzNjQzMCwicGF0aCI6Ii82OTI0NjIyLzM3OTk0OTAwOC1kYmRmODc1NC0yYTg4LTQ0MmUtODc2Zi0zMTZmMWZhZWRiMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMDYwNzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWMwMWVmYzg4YzM3YTVlM2NlMjQwMzRiNzRiYjczZThhMjFkMWRkNWFiNDViNjE0OTJlN2EzMTBiYmNkNmFmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dZaEqp-JDtDhjmgvPFM2pmR8uuRxmHzV66NUOepZuF4)

Oh! Sorry, this selection of region didn't work until I uninstalled the hacs and reinstalled, now it worked the first time without problems, thank you so much!!!
(I wish my other air conditioner could be integrated into its integration)
