### ISSUE TITLE
Temperature target trigger

### ISSUE THREAD

**Issue by Feramance** [mill1000/midea-ac-py#263]
Is it possible to have a trigger for when the target temperature is changed. For example if the temperature via the remote is changed from 22 to 21, the trigger runs an automation to set the temperature to 22 again?

![image](https://github.com/user-attachments/assets/908ae1e0-5fc4-4cec-aace-406643a5cfef)

**Comment by mill1000** [comment]
Hi, I don't control what device triggers are available. That is part of the HA core.

However, you can achieve what you want with a numeric state trigger.

e.g.
![image](https://github.com/user-attachments/assets/75f374a0-0507-47d7-ada9-1f3c7d6d528e)
