### ISSUE TITLE
HVAC mode change - add new trigger

### ISSUE THREAD

**Issue by Feramance** [mill1000/midea-ac-py#264]
Is it possible to have an option added for `on` to trigger when the AC is switched on?

![image](https://github.com/user-attachments/assets/5db67572-43e7-40ed-91dc-19cc632c9978)

**Comment by mill1000** [comment]
Again, I don't control what triggers are available. Those are defined by the HA core.

You can achieve what you want with the `not_to` or `not_from` [state triggers](https://www.home-assistant.io/docs/automation/trigger/#state-trigger). These are only available in YAML mode.
