### ISSUE TITLE
Frost Protection not working

### ISSUE THREAD

**Issue by ruteclrp** [mill1000/midea-ac-py#267]
I have an Apollo 9000 split unit labeled "Andersen Electric". It appears to be a straight relabeled Midea unit, and everything works - except the Away mode does not trigger the Frost Protection mode. 

I can enable FP from the IR remote. 

Selecting e.g Drying mode from the integration takes the unit out of FP. Changing to Heat mode works, but selecting Away mode only result in a "bip" from the unit and nothing else. 

Wondering how I can add more substance to this issue - and also if it really just is something not intended to work with the present function set in the integration?

**Comment by mill1000** [comment]
Hi.

The away/freeze protection mode has been tested successfully by a few other users. However it wouldn't be the first time a device has only had a function available via the remote.

A. If you enable FP mode via the remote, does HA switch to the "Away" preset?
B. Does the OEM app provide an option for FP mode? Or is it only on the remote?

**Comment by ruteclrp** [comment]
Hi, thanks,

A. when I use the 'away' preset, it is not really working, in that it revert to 'none' after a few seconds
the debug log records this string: 
2024-10-30 20:00:49.095 WARNING (MainThread) [msmart.device.AC.device] Device is not capable of property <PropertyId.IECO: 227>. 

B. The OEM app does no provide an option for the FP mode. Enabling it only via the IR remote.

**Comment by ruteclrp** [comment]
Additionally,

A. changing the device to FP on the IR remote has no effect on the preset value - it is always 'none'

**Comment by mill1000** [comment]
> 2024-10-30 20:00:49.095 WARNING (MainThread) [msmart.device.AC.device] Device is not capable of property <PropertyId.IECO: 227>.

This is irrelevant to your issue although I'm not sure why it appeared.

Can you post the full debug log after restarting HA?

> B. The OEM app does no provide an option for the FP mode. Enabling it only via the IR remote.
> A. changing the device to FP on the IR remote has no effect on the preset value - it is always 'none'

Most likely this means the device doesn't expose the FP control and there's nothing we can do.

**Comment by mill1000** [comment]
Closing as stale.
