### ISSUE TITLE
A climate is configured with no preset modes

### ISSUE THREAD

**Issue by keniji** [mill1000/midea-ac-py#27]
I also just migrated from mac-zhou's Midea integration and thanks for make this integration alive again!

I have two climates of Hualing, which is a sub-brand of Midea. These two climates were not bought together but are the same model `N8HE1`.
When both climates were added by mac-zhou's integration, they both had preset modes: `none`, `eco`, `sleep` and `boost`, but when they are added by this integration, only one of them have the same right preset modes, while another one only have `none`.
I tried the `midea-discover` command from `msmart-ng`, both of them have the same properties below:
```
'port': 6444,
'online': True
'supported': True
'type': <DeviceType.AIR_CONDITIONER: 172>
```
I also tried `Configure manually`, but the added entity still has the same issue.
Could you please kindly advise what steps I can do to troubleshoot this issue? Thanks in advance!

**Comment by mill1000** [comment]
Hm... Interesting. This is mostly likely due to this change (https://github.com/mill1000/midea-ac-py/commit/f3bdd92ce48816ad69d084c89e3d428071132844) where we only show presets if the device says it supports them.

If you enable debug logging, you should see a message about "capabilities"
```
logger:
  default: warning
  logs:
    custom_components.midea_ac: info
    msmart: debug
```
I wonder if the manufacturer originally shipped some units without the correct capabilities and later fixed it.


Anyway, the fix would probably be to introduce an integration options to show all presets regardless of the reported capabilities.

**Comment by mill1000** [comment]
I went ahead and added an option to "show all presets". You can enable it by clicking the "Configure" button on the integration.
![image](https://github.com/mill1000/midea-ac-py/assets/6924622/a9f7328d-69b1-4dda-8301-8e30c47a6f80)


Feel free to re-open the issue if this doesn't address your problem.

**Comment by keniji** [comment]
Thanks for your quick response!

I updated this integration, re-added the climate, which would not show its preset modes previously, and this time it shows all the preset modes, even without `Show All Presets` checked!

**O_o???**

I then go to another HASS, which has an old version `2023.9.1` integration, and found this climate has preset modes now, without re-adding it! Not sure why, maybe the integration need to wait the climate to report?

Anyway, since this issue is fixed, let's leave it closed, and thanks again for your job!

**Comment by mill1000** [comment]
Odd indeed. It's possible the "get capabilities" message timed out on one device and so it didn't know which presets to populate.

Anyway. Glad it's working. Let me know if you have other issues.

**Comment by keniji** [comment]
Hi, me again..
I just found one of my climate does not show its preset modes again, even after I enabled **Show All Presets**, while another one is normal (but I don't remember if this is the same one, which worked fine when I posted this issue on Sep).
I again tried it on a test environment (HASS) and getting the same issue, so I think this is something with the packets from the climate, but how can I fix this issue?

Update:
I did some test and finally found that after I turned my climate to cool mode (not have tried heat mode since it's not cold enough 😉), the preset modes will be shown again automatically, even when the climate is turned off and be added again.
I guess it might because I haven't turn on that climate for some time..

**Comment by mill1000** [comment]
The displayed preset modes in HA does depend on the current operation mode (or if OFF, the previously selected mode). This happens regardless of the "Show All Presets".

Currently the possible presets vs operation modes are
* Cool -> None, Eco, Boost, Sleep
* Heat -> None, Away, Boost, Sleep
* Dry -> None, Eco
* Fan Only -> None
* Auto -> None, Eco, Sleep, Boost
