### ISSUE TITLE
Network timeout

### ISSUE THREAD

**Issue by stamatakisa** [mill1000/midea-ac-py#270]
I have this issue with timeout.
 I want to increase this time to stop this problems 

Πηγή: custom_components/midea_ac/coordinator.py:39
ενσωμάτωση: Midea Smart AC ([τεκμηρίωση](https://github.com/mill1000/midea-ac-py), [ζητήματα](https://github.com/mill1000/midea-ac-py/issues))
Πρώτη εμφάνιση: 11 Νοεμβρίου 2024 στις 19:13:37 (24 εμφανίσεις)
Τελευταία καταγραφή: 12:55:32

No response from 192.168.88.157:6444 in 6.010000 seconds.
Network timeout 192.168.88.57:6444: No response from host.
No response from 192.168.88.57:6444 in 6.010000 seconds.
Network timeout 192.168.88.108:6444: No response from host.
No response from 192.168.88.108:6444 in 6.010000 seconds.
-->

**Comment by stamatakisa** [comment]
I want to increase this time to stop this problems. or something else.. to stop this error.
thanks

**Comment by mill1000** [comment]
This is a fairly common problem. Try the following:
https://github.com/mill1000/midea-ac-py?tab=readme-ov-file#resolving-connectivity-issues

**Comment by mill1000** [comment]
Closing as stale. Please re-open as needed.
