### ISSUE TITLE
Activate ifeel mode or use a different sensor

### ISSUE THREAD

**Issue by davedjmd** [mill1000/midea-ac-py#271]
How can I activate the IFEEL sensor from the remote control through the integration, or use another sensor, e.g., from Home Assistant, for the room temperature in the Thermostat card? 
I can only activate this via the remote control. This action must also be possible through the Midea-AC integration. Can someone help me with this? Thanks to everyone!

**Comment by mill1000** [comment]
The integration can enable `follow_me` but support is very device dependent. e.g. some devices only respond to the remote.

See the following for more information:
https://github.com/mill1000/midea-msmart/pull/91
https://github.com/mill1000/midea-ac-py/issues/229
 
If you want to use a custom sensor (e.g. from Home Assistant), the only option is to setup an ESPHome with an IR transmitter: https://esphome.io/components/climate/midea#additional-control-options-using-ir-commands

**Comment by mill1000** [comment]
Closing as duplicate.
