### ISSUE TITLE
Integration does not start after HA update

### ISSUE THREAD

**Issue by Szerszuu** [mill1000/midea-ac-py#278]
Hi,

Please see below error from log:

ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'midea_ac': Requirements for midea_ac not found: ['msmart-ng>=2024.9.0'].

I saw earlier post about it, but it advised to delete msmart folder. I cant find/access it via Studio Code.  Below is the discussion I found.
https://community.home-assistant.io/t/custom-integration-requirements-failing-to-update/772204/21

HA versions:
 Core 2024.12.4
Supervisor 2024.12.0
Operating System 14.0 

Thanks in advance

**Comment by mill1000** [comment]
Did you try accessing the folder via the Advanced SSH Add-on? 

You could also possibly be encountering this issue
https://github.com/mill1000/midea-ac-py/issues/274

**Comment by Szerszuu** [comment]
Thanks, I will check.

**Comment by Szerszuu** [comment]
Just to report that after latest HA update it is working properly. Thank you!

**Comment by mill1000** [comment]
Well cool. Glad it's working.
