### ISSUE TITLE
Device has fan speed entity only

### ISSUE THREAD

**Issue by adamivangrgic** [mill1000/midea-ac-py#279]
Hi,
I installed the latest version of the integration and when configuring devices they have only fan speed entity available.
Previously I used 2024.7.4 as this was, as far as I am aware, the last version my devices worked as expected. But recently I haven't been able to connect them due to some connection error, so I decided to try using the latest version again, but still I encounter this same problem.

Also to note that my AC isn't Midea, but Hyundai, but it has the same dongle that Midea devices use and can be controlled with their Msmart app.

[home-assistant_midea_ac_2024-12-21T11-22-24.808Z.log](https://github.com/user-attachments/files/18218431/home-assistant_midea_ac_2024-12-21T11-22-24.808Z.log)

I coultn't download diagnostics unfortunately.

**Comment by mill1000** [comment]
Your log shows that the underlying library is stuck at 2024.5.4, you likely are encountering something like the following:

> 
> We've seen something like this a few times (#223, #255). It seems that certain environment's don't properly install dependencies: https://github.com/home-assistant/core/issues/127966
> 
> You can try clearing your `/config/deps`, or you can try a number of the workarounds presented in https://github.com/home-assistant/core/issues/127966.
> > This was resolved in the above community thread.
> > 
> > In summary, both users had older versions of `msmart-ng` in their `/config/deps` directory, The recommended resolution was to remove all the contents of `/config/deps` as it is generally deprecated.
> > 
> > @dj21d Left specific instructions on removing the directory via the SSH Add-on here:
> > 
> > https://community.home-assistant.io/t/custom-integration-requirements-failing-to-update/772204/23?u=mill1000
> 
>

**Comment by adamivangrgic** [comment]
Thank you, looks like that was the problem. I cleaned out the deps directory and it's working perfectly.
