### ISSUE TITLE
Freeze Protection (FP) mode

### ISSUE THREAD

**Issue by tronsdal** [mill1000/midea-ac-py#280]
Is it possible to add freeze protection mode? This feature is in the smarthome app.
![IMG_0309](https://github.com/user-attachments/assets/5cfbe0d0-962f-4998-950b-50984d94e54c)

**Comment by mill1000** [comment]
Freeze protection mode is implemented as the "Away" preset. It should be visible if your device indicates support for it. Otherwise you can use the "Show All Presets" integration option to force support for it.

**Comment by tronsdal** [comment]
Great, thanks. That worked perfectly :-)
