### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by ZIZNAH** [mill1000/midea-ac-py#29]
My AC is not working right now due to your request for mac-zhou/midea-ac-py removal.
I switched from mac-zhou/midea-ac-py, but I can't configure it according to the documentation, I don't know where to find the app_key: midea_app_api_key, I searched in "美的美居" but I can't find this api_key, can you answer? Can you answer this question?

**Comment by mill1000** [comment]
Hi.

Sorry for the trouble.

Configuring this extension is identical to mac-zhou/midea-ac-py. If you didn't need a key previously, you don't need one now.

If you used to configure via YAML, you can still use the "manual configuration" option.

**Comment by ZIZNAH** [comment]
hi

Thanks for your reply, I have reconfigured on midea_ac,thanks!
