### ISSUE TITLE
LED toggle button not working

### ISSUE THREAD

**Issue by paradox37** [mill1000/midea-ac-py#34]
Hello,

I have Vivax AC which is just rebranded Midea AC. It supports turning off LED display by remote, but nothing happens when I try via this integration to turn it OFF. After reopening configuration for it, it goes back to ON. Anything you can do about it ?

**Comment by mill1000** [comment]
Hi,

Thanks for using the project. 

Some device need a different message to control the display. This has been reported already in #21 and I've got an issue open for it here: https://github.com/mill1000/midea-msmart/issues/53

I'll be closing this issue as duplicate for now.
