### ISSUE TITLE
Incorrect target temperature, unable to set target temperature to 16 celsius

### ISSUE THREAD

**Issue by trvboro** [mill1000/midea-ac-py#39]
I have Midea Mission Pro 9, which is a model of Midea's AC imported and sold by Finnish distributor Onninen. If I set the temp to 16 degrees celsius using Midea Air App, the temp is incorrectly reported as 17 degrees by msmart-ng (version 2023.9.5):

INFO:msmart.cli:{'ip': '10.0.0.123', 'port': 6444, 'id': 0, 'online': True, 'supported': True, 'type': <DeviceType.AIR_CONDITIONER: 172>, 'name': None, 'sn': None, 'key': '[removed]', 'token': '[removed]', 'power': True, 'mode': <OperationalMode.HEAT: 4>, 'fan_speed': <FanSpeed.AUTO: 102>, 'swing_mode': <SwingMode.VERTICAL: 12>, **'target_temperature': 17.0**, 'indoor_temperature': 20.0, 'outdoor_temperature': 11.5, 'eco': False, 'turbo': False, 'freeze_protection': False, 'sleep': False, 'display_on': True, 'beep': False, 'fahrenheit': False}

If I set the temp to 17 degrees or higher using Midea Air App, msmart-ng reports the temperature correctly. I am also unable to set the temp to 16 degrees using msmart-ac-py. The following warnings get logged when I attempt it:
hass             | 2023-09-20 20:34:19.225 WARNING (MainThread) [msmart.device.AC.device] Device is not capable of operational mode 4.
hass             | 2023-09-20 20:34:19.231 WARNING (MainThread) [msmart.device.AC.device] Device is not capable of swing mode 12.
hass             | 2023-09-20 20:34:19.460 WARNING (MainThread) [msmart.device.AC.command] Unknown capability. ID: 0x 610, Size: 1.

**Comment by mill1000** [comment]
Can you enable debug logging and post logs when you attempt to change the target temperature?

> hass | 2023-09-20 20:34:19.225 WARNING (MainThread) [msmart.device.AC.device] Device is not capable of operational mode 4.
> hass | 2023-09-20 20:34:19.231 WARNING (MainThread) [msmart.device.AC.device] Device is not capable of swing mode 12.
> hass | 2023-09-20 20:34:19.460 WARNING (MainThread) [msmart.device.AC.command] Unknown capability. ID: 0x 610, Size: 1.

These seem unrelated to the target temperature problem. These look more like the capability parser got some bad data (which shouldn't happen).

**Comment by trvboro** [comment]
I enabled debug logging and started looking into the state response payload... based on msmart-ng code, the target temperature is read from byte 2. Here's payloads while increasing target temp from 16.0 to 20.0 degrees:
```
16.0: c00181667f7f003c00000060560400420000000000000048
16.5: c00191667f7f003c00000060560400440000000000000049
17.0: c00181667f7f003c0000006156050036000000000000004a
17.5: c00191667f7f003c0000006156050028000000000000004b
18.5: c00182667f7f003c0000006156060028000000000000004c
19.0: c00192667f7f003c0000006156060028000000000000004d
19.5: c00183667f7f003c0000006156070028000000000000004e
20.0: c00193667f7f003c00000061570700550000000000000050
          ^^                    ^^
           2                    13
```
Looks like the target temperature is presented in byte 13 as well, but without the decimal part. The halfs only show up in byte 2.

It seems that the client might need to be more intelligent in interpreting the payload. In the protocol file, I can see that there's different parsing used for certain payload values on based on the device serial number.

**Comment by trvboro** [comment]
MideaUART has support for the new temperature payload. This can probably be directly applied here: https://github.com/dudanov/MideaUART/commit/3bbd505ee58792a620ad115f9f26652b688f58e3

**Comment by pauliborodulin** [comment]
Closing this as this is an issue in underlying library msmart-ng. Created a new issue for it: https://github.com/mill1000/midea-msmart/issues/77

**Comment by mill1000** [comment]
Nice find. Closing this issue in favor of the msmart-ng issue
