### ISSUE TITLE
Bill control, power consumption monitoring in HA

### ISSUE THREAD

**Issue by csibe1999** [mill1000/midea-ac-py#5]
I would like to ask 2 feature request.

In MsmartHome app I can set "Bill Control". It is very useful feature to reduce your power consumption. I would like to use this feature in HA as well. 

Sometime I forget to turn on "Bill control" feature. I want to create automatization to notify me if the AC use much energy to able to do that I should get the AC power consumption  in HA.

Thanks

**Comment by mill1000** [comment]
>In MsmartHome app I can set "Bill Control". It is very useful feature to reduce your power consumption. I would like to use this feature in HA as well.

Some functions of the MsmartHome app aren't device functions but functionality that comes from the app/cloud. This might be one of them.  Does the device have any indication that "bill control" is enabled or is it app only?

> Sometime I forget to turn on "Bill control" feature. I want to create automatization to notify me if the AC use much energy to able to do that I should get the AC power consumption in HA.

This might be possible. My units don't support this function and I won't be able to test but there's some code in dudanov/MideaUART I could test.

**Comment by csibe1999** [comment]
Then I think the "bill control" is app only feature because I can't set bill control via remote controller. When I set the bill control the AC unit has only a beep sound. So is this feature possible to implement into your addons? If yes can you help me how to set up a local env and how can I test my code locally with my own AC?

**Comment by mill1000** [comment]
I think you could re-implement a feature like "bill control" with Home Assistant as long as you had power consumption information.

**Comment by mill1000** [comment]
I have begun working on this feature request. If anyone is available for testing that would be greatly appreciated

**Comment by mill1000** [comment]
Progress is being made. msmart-ng 2024.7.0 supports energy usage requests. Now we just need to integrate it.
