### ISSUE TITLE
Toggle display not supported but present in manual

### ISSUE THREAD

**Issue by syntesys87** [mill1000/midea-ac-py#6]
Hello,

I have Clivet climas that are working with Midea Smart AC appliances and it's full operational with your implementations, except for one thing: I saw from commits that there is a switch for toggle the display on and off, tried to force the enabling of the switch but on/off does not work with the display; in the manual I found that I can turn on/off display pressing the LED button in the remote control. How can I verify how it works and implement it in the plugin?

Thank you.

**Comment by mill1000** [comment]
Does the original app have control for the LED display?

Can you provide a link to the manual?

If the only way to control the LED display is via the remote or a physical button it might not be possible for this integration to control it.

**Comment by syntesys87** [comment]
In the next update I see the led button in the app, is available but when I click it it says "feature not available for your model, please use remote control". So, not compatible. 
This is the link to the manual: [LINK](https://www.google.com/url?sa=t&source=web&rct=j&url=https://clivetbelux.be/assets/manuel-d-installation-et-utilisation.pdf&ved=2ahUKEwjz39ry5rb_AhVEyAIHHf0fBcEQFnoECBIQAQ&usg=AOvVaw1JH_BOgZXnMsO1xioVwl90)

**Comment by mill1000** [comment]
Unfortunate. What a silly feature to leave to the remote only. I'll be closing this issue since it seems there's nothing we can do about it.
