### ISSUE TITLE
Incorrect temperature values presented by the AC's sensor

### ISSUE THREAD

**Issue by danihorvath** [mill1000/midea-ac-py#63]
Hi. Thanks for maintaining this integration.

Currently I'm using my AC device (Midea Xtreme Save Pro) in heating mode. There are several temperature sensors in the room, all showing around 20°C, while the integration's thermostat presents values well above 25-30°C. 

After turning off the AC, the reported temperature slowly (in about 30-40 minutes) decreases to the correct value. I believe this is because the integrated thermometer is built into the overheated indoor unit. The "Follow me" function works great, after activating it, the remote starts sending correct values - but it only does while the AC is running.

I totally understand that we are limited by the product's capabilities, but should be there a solution to not present misleading information. I had an idea of an option to select an independent sensor in the integration settings, which will overwrite the thermostat's value.

What do you think?

**Comment by mill1000** [comment]
Hi. Thanks for using the integration!

> Currently I'm using my AC device (Midea Xtreme Save Pro) in heating mode. There are several temperature sensors in the room, all showing around 20°C, while the integration's thermostat presents values well above 25-30°C.

Ah, yes I've noticed similar behavior on one of my window AC units. It will often report temperatures below the true ambient 

> I totally understand that we are limited by the product's capabilities, but should be there a solution to not present misleading information. I had an idea of an option to select an independent sensor in the integration settings, which will overwrite the thermostat's value.

Personally I think this is out of scope of the integration. In my opinion, the integration should accurately report the information obtained from the device.

Instead, you could try to solve this problem on the "frontend". 

One option. Create a template climate entity (https://github.com/jcwillox/hass-template-climate) and use your other sensor entities to report temperature.

Another option is the mini-climate-card (https://github.com/artem-sedykh/mini-climate-card) which lets you specify a different entity for the current temperature.

> The "Follow me" function works great, after activating it, the remote starts sending correct values - but it only does while the AC is running.

You may also want to look into ESPHome. A node can be configured to transmit any HA sensor value for the follow me feature.

https://esphome.io/components/climate/midea#additional-control-options-using-ir-commands

**Comment by danihorvath** [comment]
Just had time to set up the hass-template-climate, and it works perfectly. 
I might look into the ESPHome solution too. Thanks for the tip.

**Comment by mill1000** [comment]
Cool, glad that's working out for you.
