### ISSUE TITLE
HVAC problem with multiple commands at once

### ISSUE THREAD

**Issue by eonnet** [mill1000/midea-ac-py#66]
When i have an automation or script wher it turns on the AC sets the temperature and set the fan mode the ac turns off immediately after the power on and also sometimes if you send command for temp and fan while is on it increase the temp and after one second it reverts back to the original temp.

**Comment by mill1000** [comment]
Hi,

Can you enable debug logging, run your script and then post the logs here?

**Comment by eonnet** [comment]
Sorry my mistake i was using another hacs integration, injust tested yours and everything works great i’m switching to yours :)

**Comment by mill1000** [comment]
Oh well that's great to hear! Let me know if anything else is off.
