### ISSUE TITLE
Fan Mode High incorect

### ISSUE THREAD

**Issue by eonnet** [mill1000/midea-ac-py#67]
When i select a fan mode high in the Home Assistant it turns on the fan mode in Auto Mute in the Smart Home app for midea ( or silent as shown in other midea integrations in home assistant)
![IMG_1762](https://github.com/mill1000/midea-ac-py/assets/53785707/4444291b-063d-43ad-aecd-d9b266c99480)
![IMG_1761](https://github.com/mill1000/midea-ac-py/assets/53785707/5dbc525f-af61-4816-9801-2da8aa2f4ef7)
![IMG_1760](https://github.com/mill1000/midea-ac-py/assets/53785707/85ff184b-ec58-4985-b330-8bb0745de0ca)

when i choose high in the app it turns on auto mode in home assistant.

When i select auto mode in home assitant its ok.
Other modes are correct

**Comment by mill1000** [comment]
This is probably due to mill1000/midea-msmart#95

To be sure,  can you enable debug logging, toggle the fan speed from "Auto" to "High", and then post the logs here?

**Comment by eonnet** [comment]
I enabled debuging on the integration but dont know where to find the logs

**Comment by mill1000** [comment]
If you disable debug logging it will automatically download them for you

**Comment by eonnet** [comment]
[home-assistant_midea_ac_2023-12-22T18-48-13.315Z.log](https://github.com/mill1000/midea-ac-py/files/13756089/home-assistant_midea_ac_2023-12-22T18-48-13.315Z.log)
here it is

**Comment by mill1000** [comment]
Thanks. Can you collect 1 more log? This time set the fan to "High" in the app

**Comment by eonnet** [comment]
[home-assistant_midea_ac_2023-12-22T20-50-57.720Z.log](https://github.com/mill1000/midea-ac-py/files/13756657/home-assistant_midea_ac_2023-12-22T20-50-57.720Z.log)
Here it is

**Comment by mill1000** [comment]
Thanks. That's all I need. I have a PR with a fix that I'll get merged and released https://github.com/mill1000/midea-msmart/pull/104

**Comment by eonnet** [comment]
When will you push an update for the hacs integration also? I see that you updated the python library

**Comment by mill1000** [comment]
Done :)

**Comment by eonnet** [comment]
Working perfectly :)
