### ISSUE TITLE
Fan position selection

### ISSUE THREAD

**Issue by gapple** [mill1000/midea-ac-py#69]
My air conditioner (Midea Duo - MAP12S1TBL) has an option to set the fan position to one of five options in the app:
<img src="https://github.com/mill1000/midea-ac-py/assets/458809/4289ae3d-b568-48ee-84c7-f50a710cdbb0" width="30%">

If Swing has been enabled, the current fan position is no longer indicated until a new option is selected:
<img src="https://github.com/mill1000/midea-ac-py/assets/458809/e8cd74dc-ec8b-43ba-b49a-8dac4b4a384e" width="30%">

The fan position has an odd side effect of limiting the max power of the compressor (to ~50% in the lowest position), but I've used this to control whether a separate dehumidifier on the same circuit will turn on (currently via an `input_boolean` that I manually toggle when adjusting the fan) to avoid tripping the circuit's breaker.  I would like to be able to automate positioning the fan so that I can allow the dehumidifier to run when the AC doesn't need to run at full power, and disable the dehumidifier when max cooling is needed.

**Comment by mill1000** [comment]
Hi,

That functionality likely requires the "new" protocol which I have yet to implement. (https://github.com/mill1000/midea-msmart/issues/97)

Could you query your device capabilities with msmart-ng?
```
msmart-ng query <device-ip-address> --auto --debug
```

**Comment by gapple** [comment]
<details>
  <summary>msmart-ng query <device-ip-address> --auto --debug</summary>
```
% msmart-ng query 10.0.1.38 --auto --debug
DEBUG:asyncio:Using selector: KqueueSelector
INFO:msmart.cli:Discovering 10.0.1.38 on local network.
DEBUG:msmart.discover:Discovery sent to 10.0.1.38:6445.
DEBUG:msmart.discover:Discovery sent to 10.0.1.38:20086.
DEBUG:msmart.discover:Waiting 5 seconds for responses...
DEBUG:msmart.discover:Discovery response from 10.0.1.38: 837000c8200f00005a5a0111b8007a8000000000fc49080603011814a45a0000008100000000000000000180000000005d3fa2d434acbba50a889455997b0ead6dcfaab77643ab34e626497d6a2b391bbda126f57f76ebd840f047d8cddcf6acbe13039212d3045b11a1c4d835687a923ed4f3daa3f9583330ae6009c024d28c76fc37a5e419f388adfc90021b29b8b14bdfb3e16e33d88768cc4c3d0658937d0bb19369bf0317b24d3a4de9e6a13106e4f4ef2961ca8a9916ee7a9425326cc195c778729dbdf9a8aa37c27d76f89273
DEBUG:msmart.discover:Decrypted data from 10.0.1.38: 2601000a2c19000030303030303050303030303030305131373038364345413330314134303030300b6e65745f61635f303141340000870002000000000000000000ac00acac000000007086cea301a4150023092237000301000000000000000000000000000000000000000000000000000000000000000000
INFO:msmart.cloud:Using Midea cloud server: https://mp-prod.appsmb.com (China: False).
INFO:httpx:HTTP Request: POST https://mp-prod.appsmb.com/mas/v5/app/proxy?alias=/v1/user/login/id/get "HTTP/1.1 200 "
DEBUG:msmart.cloud:API response: {"code":"0","msg":"ok","data":{"loginId":"[----]"}}
DEBUG:msmart.cloud:Received loginId: [----]
INFO:httpx:HTTP Request: POST https://mp-prod.appsmb.com/mas/v5/app/proxy?alias=/mj/user/login "HTTP/1.1 200 OK"
DEBUG:msmart.cloud:API response: {[----]}
DEBUG:msmart.cloud:Received accessToken: [----]
DEBUG:msmart.discover:Fetching token and key for udpid '[----]' (little).
INFO:httpx:HTTP Request: POST https://mp-prod.appsmb.com/mas/v5/app/proxy?alias=/v1/iot/secure/getToken "HTTP/1.1 200 OK"
DEBUG:msmart.cloud:API response: {"code":"0","msg":"ok","data":{"tokenlist":[{"udpId":"[----]","key":"[----]","token":"[----]"}]}}
INFO:msmart.lan:Creating new connection to 10.0.1.38:6444.
DEBUG:msmart.lan:Connected to 10.0.1.38:6444.
INFO:msmart.lan:Authenticating with 10.0.1.38:6444.
DEBUG:msmart.lan:Sending data to 10.0.1.38:6444: 837000402000000004c4f1d82ed70d62d2967506b9b390500d32731da5024950c567a06c08c44b4f3bc037f2e465229a5215d003d4ed08fb0643356da3b4a931c8b6268f85839b21
DEBUG:msmart.lan:Received data from 10.0.1.38:6444: 83700005200f00204552524f52
DEBUG:msmart.discover:Fetching token and key for udpid '[----]' (big).
INFO:httpx:HTTP Request: POST https://mp-prod.appsmb.com/mas/v5/app/proxy?alias=/v1/iot/secure/getToken "HTTP/1.1 200 OK"
DEBUG:msmart.cloud:API response: {"code":"0","msg":"ok","data":{"tokenlist":[{"udpId":"[----]","key":"[----]","token":"[----]"}]}}
INFO:msmart.lan:Authenticating with 10.0.1.38:6444.
DEBUG:msmart.lan:Sending data to 10.0.1.38:6444: 83700040200000012530b250332c0542301a5a8f3e42c0c9da389efe245804e44a184c29a8b9d00370b42011b7258232c3aed26d6934a52b90ec3d78c10d7ab54710628171c22cea
DEBUG:msmart.lan:Received data from 10.0.1.38:6444: 837000402001e9471f955171c99ac58c85c5d815a05e609a134024ed3830dc134b89dc7e1b549e34dc006bace8a7d72816e1947354e08b57c713fe7c3bba2fd3c84a9a2cecc1f0f9
INFO:msmart.lan:Authentication successful. Expiration: 2024-01-03T18:08:10, Local key: [----]
DEBUG:msmart.base_device:Sending command to 10.0.1.38:6444: aa21ac8d000000000003418100ff03ff000200000000000000000000000003016971
DEBUG:msmart.lan:Sending packet to 10.0.1.38:6444: 5a5a01116800200000000000010b080603011814a45a000000810000000000000000000000000000b8436dd15e84d5a4fc6fbf77d2b12486e10c552981b23022cb71ea0fc54dc25ecfa0ce55888ac57fc42a7eacc3285d37106c3450604a2818f70378a7fdb804e1
DEBUG:msmart.lan:Sending data to 10.0.1.38:6444: 8370008e2066a2c43c977766b6078eecafc3e3f7a044aee77d3f18b2214c482ec1a7a00bedb3aff9d080c59a55b54ef1efdfeb8134cea1a65b330808e774b699ab46ec6025015353a05c1717dae61ace9da46b0f941de4ece5296ba87971910e195df1f2fa6b819d28446e1677d13f9c2d6a6056ac028844f2a1a32c98e8a3aa2c8287fe269d7027dc89a4110dd4960ad442d1b3b29d
DEBUG:msmart.lan:Received data from 10.0.1.38:6444: 8370008e206397f837d565e2c0cf0577e3c00352db39c2571b24811a31bdbdda1ec3cb6466d2eb0bf7bdd4e5532750e4be879bd966c86a82f70adb5648934ffe1d4f3e1827f4320842794d2153e677009f53badda22773cca7423c6b22c3c55fc71c1d56e253ceefd0ff25abce884a48046c204bab8176026654c5dc6f9c0906d989724204374f21904ccb79b34aba9e9dd6785f68ec
DEBUG:msmart.lan:Received packet from 10.0.1.38:6444: 5a5a01116800208000000000cc4b080603011814a45a000000810000000000000000018000000000b2742500b672a18cc48ade564713596b36a8ebe0df810dfd5c1202d072096b5a0a3cb36408b232f4e842a5019bd6fc3aa38b043e3f2d3cc53d44596755d1a3db
DEBUG:msmart.lan:Received response from 10.0.1.38:6444: aa23ac00000000000303c001a1197f7f003000000054552000000000000000000001d8e0
DEBUG:msmart.base_device:Response from 10.0.1.38:6444 in 0.420000 seconds.
DEBUG:msmart.device.AC.command:State response payload: c001a1197f7f003000000054552000000000000000000001
DEBUG:msmart.discover:Discovered 1 devices.
INFO:msmart.cli:Querying device state.
DEBUG:msmart.base_device:Sending command to 10.0.1.38:6444: aa21ac8d000000000003418100ff03ff000200000000000000000000000003028b4e
DEBUG:msmart.lan:Sending packet to 10.0.1.38:6444: 5a5a011168002000000000002e0e080603011814a45a000000810000000000000000000000000000b8436dd15e84d5a4fc6fbf77d2b1248672946460bceafc6eae86e4200896522a734e1faa37ce959a047497632b36c8a80fcac0b1cafe1afb29a9c86eba1ab77d
DEBUG:msmart.lan:Sending data to 10.0.1.38:6444: 8370008e20668a0886822f905aecd0b8be853cb5e892d419a6edbe34eb66a39790d5d80b2f9dfaee577c16895d06f987a4046ab8a8b80988b458ee797626f1042ddeda8324601a981f29686c6bd77cfcce00f908bee9d59e86ec6e36261d0644ba505facb76e189e4fc25515dcc5b3bf45c57be6c31fdf3dcb4b53cc0650ba91c57bc4d1c8363641536663667eabb79e38c4747af272
DEBUG:msmart.lan:Received data from 10.0.1.38:6444: 8370008e206328eb2e194f41ca037197ec2c8ea1d054c5ca1cea8ecf177a93fba0bed544b28fbccb2ed0dd25e5827248371d9621dd7f6c32db580c8054f1bd8deb48b1f211a92fdea3a9793c861a86d691dd0f142afb747b6db9a3b6879a0caf7b6b00dd7ea3779a726e94dbd07833396fb5280eea4182abf206afd127af49f85d0a51a31afa4100e88927db70bba0a12bd08009ed55
DEBUG:msmart.lan:Received packet from 10.0.1.38:6444: 5a5a01116800208000000000638e080603011814a45a000000810000000000000000018000000000b2742500b672a18cc48ade564713596b36a8ebe0df810dfd5c1202d072096b5a0f56ad588e3c2fd94e0a207a8e02ff0bf383276dce31ce41573f7935a315655a
DEBUG:msmart.lan:Received response from 10.0.1.38:6444: aa23ac00000000000303c001a1197f7f0030000000545520000000000000000000023a7d
DEBUG:msmart.base_device:Response from 10.0.1.38:6444 in 0.120000 seconds.
DEBUG:msmart.device.AC.command:State response payload: c001a1197f7f003000000054552000000000000000000002
INFO:msmart.cli:{'ip': '10.0.1.38', 'port': 6444, 'id': [----], 'online': True, 'supported': True, 'type': <DeviceType.AIR_CONDITIONER: 172>, 'name': 'net_ac_01A4', 'sn': '[----]', 'key': '[----]', 'token': '[----]', 'power': True, 'mode': <OperationalMode.FAN_ONLY: 5>, 'fan_speed': 25, 'swing_mode': <SwingMode.OFF: 0>, 'target_temperature': 17.0, 'indoor_temperature': 17.0, 'outdoor_temperature': 17.5, 'eco': False, 'turbo': False, 'freeze_protection': False, 'sleep': False, 'follow_me': False, 'display_on': True, 'beep': False, 'fahrenheit': False}
```
</details>

**Comment by mill1000** [comment]
Sorry I meant for you to query the capabilities, not the device state.

The command should have been
```
msmart-ng query <device-ip-address> --auto --debug --capabilities
```

**Comment by gapple** [comment]
These look like the relevant lines, let me know if there's something else important I've cut out

<details>
  <summary>msmart-ng query <device-ip-address> --auto --debug --capabilities</summary>

```
DEBUG:msmart.device.AC.command:Capabilities response payload: b50814020100150201001e020100170201021a02010010020101250207203c203c203c00240201010102
DEBUG:msmart.device.AC.command:Raw capabilities: {'heat_mode': False, 'cool_mode': True, 'dry_mode': True, 'auto_mode': True, 'swing_horizontal': False, 'swing_vertical': True, 'anion': False, 'filter_notice': True, 'filter_clean': False, 'turbo_heat': False, 'turbo_cool': True, 'fan_silent': False, 'fan_low': False, 'fan_medium': False, 'fan_high': False, 'fan_auto': False, 'fan_custom': True, 'cool_min_temperature': 16.0, 'cool_max_temperature': 30.0, 'auto_min_temperature': 16.0, 'auto_max_temperature': 30.0, 'heat_min_temperature': 16.0, 'heat_max_temperature': 30.0, 'decimals': False, 'display_control': True}

DEBUG:msmart.device.AC.command:Capabilities response payload: b5031f0201002c020101090001010003
WARNING:msmart.device.AC.command:Unsupported capability. ID: 0x0009, Size: 1.
DEBUG:msmart.device.AC.command:Raw capabilities: {'humidity_auto_set': False, 'humidity_manual_set': False, 'buzzer': True}
DEBUG:msmart.device.AC.command:Merged raw capabilities: {'heat_mode': False, 'cool_mode': True, 'dry_mode': True, 'auto_mode': True, 'swing_horizontal': False, 'swing_vertical': True, 'anion': False, 'filter_notice': True, 'filter_clean': False, 'turbo_heat': False, 'turbo_cool': True, 'fan_silent': False, 'fan_low': False, 'fan_medium': False, 'fan_high': False, 'fan_auto': False, 'fan_custom': True, 'cool_min_temperature': 16.0, 'cool_max_temperature': 30.0, 'auto_min_temperature': 16.0, 'auto_max_temperature': 30.0, 'heat_min_temperature': 16.0, 'heat_max_temperature': 30.0, 'decimals': False, 'display_control': True, 'humidity_auto_set': False, 'humidity_manual_set': False, 'buzzer': True}
INFO:msmart.cli:{'supported_modes': [<OperationalMode.FAN_ONLY: 5>, <OperationalMode.DRY: 3>, <OperationalMode.COOL: 2>, <OperationalMode.AUTO: 1>], 'supported_swing_modes': [<SwingMode.OFF: 0>, <SwingMode.VERTICAL: 12>], 'supported_fan_speeds': [<FanSpeed.SILENT: 20>, <FanSpeed.LOW: 40>, <FanSpeed.MEDIUM: 60>, <FanSpeed.HIGH: 80>, <FanSpeed.AUTO: 102>], 'supports_custom_fan_speed': True, 'supports_eco_mode': False, 'supports_turbo_mode': True, 'supports_freeze_protection_mode': False, 'supports_display_control': True, 'supports_filter_reminder': True, 'max_target_temperature': 30.0, 'min_target_temperature': 16.0}
```
</details>

**Comment by mill1000** [comment]
Thanks, those were the lines of interest.

For now, this supporting this functionality is primarily blocked by the new protocol support: https://github.com/mill1000/midea-msmart/issues/97

**Comment by mill1000** [comment]
@gapple I've begun some work on supporting the new protocol which would enable vertical angle control.

Would you be available and willing to test? It would require installing an experimental branch and running some Python test scripts.

**Comment by parautenbach** [comment]
I can also help test this. 

Related: Is horizontal angle control an option too?

**Comment by mill1000** [comment]
Yep horizontal angle control will also be possible (assuming device support)

**Comment by mill1000** [comment]
Cool, I've put some instructions here https://github.com/mill1000/midea-msmart/issues/97#issuecomment-1936432229 where I'd like to track development

**Comment by mill1000** [comment]
@parautenbach I'm working on swing angle support right now. If you're able to test I've put some code here: https://github.com/mill1000/midea-msmart/issues/97#issuecomment-1947748486

**Comment by mill1000** [comment]
The latest release added support for this function. My devices do not support such functionality so testing was limited to some volunteers. Please report any issues you may enocunter.

**Comment by v1k70rk4** [comment]
It works perfectly for me. Thank you for the development!

**Comment by mill1000** [comment]
Glad to hear it.

**Comment by parautenbach** [comment]
> @parautenbach I'm working on swing angle support right now. If you're able to test I've put some code here: [mill1000/midea-msmart#97 (comment)](https://github.com/mill1000/midea-msmart/issues/97#issuecomment-1947748486)

My apologies for not getting to this as promised. I upgraded to the 2024.3.1 release that adds this functionality and I'm happy to say it works for me too.

**Comment by mill1000** [comment]
That's great to hear. Thanks for confirming. Got any other functionality you'd want implemented?

**Comment by gapple** [comment]
Thanks! I hope I can get more time to test future features 😄 

Position selection is working on my machine, and the value is updated after I change it through the Midea app, but doesn't get changed to 'off' when swing is enabled, like how the Midea app will unselect the positional options.  That means the entity value can't necessarily be trusted in things like automation conditions, and making sure HA sets the position would require a workaround like setting the entity to 'off' before setting it to the desired position.  
It shouldn't actually be an issue for me, since I don't use the swing feature and I think the only time the position might end up incorrect because I didn't set it is upon plugging it in / turning on power (when it always goes to Position 1 / vertical).

**Comment by parautenbach** [comment]
> That's great to hear. Thanks for confirming. Got any other functionality you'd want implemented?

Ha, thanks for the great offer!

I think the functionality of my ACs are perfectly covered. There's nothing I cannot do. :-) 

I did have a remark on the swing functionality: My one AC only supports vertical swing (horizontal needs manual adjustment) – it's a small AC. 

Does HA offer a way to limit the available features, and if it does, can the option (e.g.) for horizontal swing for a unit that doesn't support it (assuming you can get this info via the API) be omitted?

I've written a media player integration and I know it has feature flags. I'm assuming climate devices might have it too.

**Comment by mill1000** [comment]
> I did have a remark on the swing functionality: My one AC only supports vertical swing (horizontal needs manual adjustment) – it's a small AC.
> 
> Does HA offer a way to limit the available features, and if it does, can the option (e.g.) for horizontal swing for a unit that doesn't support it (assuming you can get this info via the API) be omitted?

Yes HA does have feature flags for climate entities. Other features are also controlled by properties that return supported modes, presets, etc. This _should_ all be implemented already. 

The integration should only show swing modes that are supported by the unit.
https://github.com/mill1000/midea-ac-py/blob/611f5e916f666acc4e4f51d63720c82c189f5f8b/custom_components/midea_ac/climate.py#L160-L170

If you're seeing swing modes that aren't actually supported, could you enable debug mode, reboot and post the logs here?

> I've written a media player integration and I know it has feature flags. I'm assuming climate devices might have it too.

Oh I know. I'm using it. :)

**Comment by parautenbach** [comment]
> If you're seeing swing modes that aren't actually supported, could you enable debug mode, reboot and post the logs here?

I've attached my logs. The AC of concern is the `192.168.0.114` one. 

```
2024-04-09 14:09:34.467 DEBUG (MainThread) [msmart.base_device] Response from 192.168.0.114:6444 in 0.170000 seconds.
2024-04-09 14:09:34.467 DEBUG (MainThread) [msmart.device.AC.command] Capabilities response payload: b50a12020101180001001402010115020101160201001a0201011002010
11f020100250207203c203c203c00400001000100
2024-04-09 14:09:34.467 WARNING (MainThread) [msmart.device.AC.command] Unknown capability. ID: 0x  40, Size: 1.
2024-04-09 14:09:34.468 DEBUG (MainThread) [msmart.device.AC.command] Raw capabilities: {'eco_mode': True, 'eco_mode_2': False, 'silky_cool': False, 'heat_mode'
: True, 'cool_mode': True, 'dry_mode': True, 'auto_mode': True, 'swing_horizontal': True, 'swing_vertical': True, 'power_stats': False, 'power_setting': False,
'power_bcd': False, 'turbo_heat': True, 'turbo_cool': True, 'fan_silent': False, 'fan_low': False, 'fan_medium': False, 'fan_high': False, 'fan_auto': False, 'f
an_custom': True, 'humidity_auto_set': False, 'humidity_manual_set': False, 'cool_min_temperature': 16.0, 'cool_max_temperature': 30.0, 'auto_min_temperature':
16.0, 'auto_max_temperature': 30.0, 'heat_min_temperature': 16.0, 'heat_max_temperature': 30.0, 'decimals': False}
```

Looks like the AC reports that it has a capability which it doesn't. 

>> I've written a media player integration and I know it has feature flags. I'm assuming climate devices might have it too.
>
> Oh I know. I'm using it. :)

Of course! How did I not notice...

**Comment by mill1000** [comment]
> Looks like the AC reports that it has a capability which it doesn't.

Yeah that's interesting. When I get a minute I'll review the raw capabilities payload and see if I'm parsing something incorrectly.

**Comment by mill1000** [comment]
Yeah as far as I can tell it looks like your device is just misreporting it's capabilities.

**Comment by parautenbach** [comment]
Naughty aircon. So be it!
