### ISSUE TITLE
Cannot rename device in HA

### ISSUE THREAD

**Issue by parautenbach** [mill1000/midea-ac-py#74]
Adding my new aircon (a 9000 BTU Midea Xtreme Inverter) through this integration works just fine. The `msmart` tool also reports it as supported. 

The problem is that when I rename the **device** (and choose the option for HA to also rename all associated entities with it), I end up with a broken integration: Only the climate entity gets renamed and some entities become unavailable. 

<img width="1950" alt="Screenshot 2024-01-16 at 17 08 21" src="https://github.com/mill1000/midea-ac-py/assets/743320/b1ad2d80-0565-47f5-ab17-1040fbc43da6">

<img width="1016" alt="Screenshot 2024-01-16 at 17 08 35" src="https://github.com/mill1000/midea-ac-py/assets/743320/ba8ed42b-67a1-4d6e-90ff-8a020f55cea5">

```
$ msmart-ng discover
INFO:msmart.cli:Discovering all devices on local network.
INFO:msmart.cloud:Using Midea cloud server: https://mp-prod.appsmb.com (China: False).
INFO:msmart.lan:Creating new connection to 192.168.0.xxx:6444.
INFO:msmart.lan:Authenticating with 192.168.0.xxx:6444.
INFO:msmart.lan:Authenticating with 192.168.0.xxx:6444.
INFO:msmart.lan:Authentication successful. Expiration: 2024-01-17T03:05:04, Local key: redacted
INFO:msmart.cli:Found 1 devices.
INFO:msmart.cli:Found device:
{'ip': '192.168.0.xxx', 'port': 6444, 'id': redacted, 'online': True, 'supported': True, 'type': <DeviceType.AIR_CONDITIONER: 172>, 'name': 'net_ac_0638', 'sn': 'redacted', 'key': 'redacted', 'token': 'redacted'}
```

Relevant piece of the HA log:
```
Jan 16 16:58:36 homeassistant hass[383372]: 2024-01-16 16:58:36.291 WARNING (MainThread) [msmart.device.AC.command] Unknown capability. ID: 0x  40, Size: 1.
Jan 16 16:58:36 homeassistant hass[383372]: 2024-01-16 16:58:36.426 WARNING (MainThread) [msmart.device.AC.command] Unsupported capability. ID: 0x0009, Size: 1.
Jan 16 16:58:36 homeassistant hass[383372]: 2024-01-16 16:58:36.426 WARNING (MainThread) [msmart.device.AC.command] Unsupported capability. ID: 0x000A, Size: 1.
```

**Comment by mill1000** [comment]
Hey there. I'll look into this, perhaps its related to the following changes from the HA side:
- https://developers.home-assistant.io/blog/2023/06/28/entity-name-changes/
- https://developers.home-assistant.io/blog/2022/07/10/entity_naming/

> ```
> Jan 16 16:58:36 homeassistant hass[383372]: 2024-01-16 16:58:36.291 WARNING (MainThread) [msmart.device.AC.command] Unknown capability. ID: 0x  40, Size: 1.
> Jan 16 16:58:36 homeassistant hass[383372]: 2024-01-16 16:58:36.426 WARNING (MainThread) [msmart.device.AC.command] Unsupported capability. ID: 0x0009, Size: 1.
> Jan 16 16:58:36 homeassistant hass[383372]: 2024-01-16 16:58:36.426 WARNING (MainThread) [msmart.device.AC.command] Unsupported capability. ID: 0x000A, Size: 1.
> ```
These are harmless. The last 2 will be resolved in the next msmart-ng release.

**Comment by mill1000** [comment]
Just created a PR with a potential fix: #76 

Would you be able to test? My unit is offline for the season so I can't be of much help.

**Comment by parautenbach** [comment]
Sure! I'll try my best to do it tomorrow.

**Comment by parautenbach** [comment]
@mill1000 I got around to test it.

The good news is that after renaming the device all entities are still available. 

The bad news is that only the climate entity got renamed (I picked the option to rename all entities).

**Comment by mill1000** [comment]
Hm..just did a test myself.

The first attempt was odd. Some of the entities had IDs like `sensor.none_indoor_temperature`. I removed and re-configured the device and the IDs came back as expected. I was able to successfully rename this device and it's entities.

Did you remove and re-configure your device after updating to the branch?

**Comment by parautenbach** [comment]
> Did you remove and re-configure your device after updating to the branch?

A kind of third option: I had a second climate entity that I had added (but no renaming, so it was as added) before manually updating the code. 

I repeated your steps now and I can confirm it renamed all the entities correctly. Awesome!

**Comment by parautenbach** [comment]
Sorry, should probably keep this open until merged/released. :-)

**Comment by mill1000** [comment]
Cool. I'll get this merged and released soon. I just want to perform some tests so I understand how a user updating to this change is impacted.

**Comment by parautenbach** [comment]
Thanks a mil. I'm happy to do more testing too, if needed.
