### ISSUE TITLE
Inventor device not discovered

### ISSUE THREAD

**Issue by chrisdal2000** [mill1000/midea-ac-py#75]
I have 2 acc Inventor and use that app https://play.google.com/store/apps/details?id=com.Inventor.Control&hl=el&gl=US.
I try this py (midea-ac-py) but say

msmart-ng discover
INFO:msmart.cli:Discovering all devices on local network.
ERROR:msmart.cli:No devices found.

any help?
thanks

**Comment by mill1000** [comment]
Try discovering a device with it's IP address.
```
msmart-ng discover -d <ip_address>
```

Do you know what WiFi module is in the units?

**Comment by chrisdal2000** [comment]
i try and with ip but nothing. 
When go to home, i try  to check what wifi stick has and post here.

thanks

**Comment by mill1000** [comment]
Unfortunately, it looks like devices that use "Inventor Control
 are not compatible. There's no references to msmart or midea inside the APK. They _might_ be Tuya based.

Devices that use the "INVmate II" app should be compatible.
