### ISSUE TITLE
Changing fan mode not working the first time

### ISSUE THREAD

**Issue by parautenbach** [mill1000/midea-ac-py#78]
When picking a fan mode (auto, in this case), I received this error in my log. It could be an initialisation issue, since subsequent changes didn't emit the same error. The AC was already on when I restarted HA and then tried to change the fan mode. 

```
Jan 22 13:39:39 homeassistant hass[372729]: 2024-01-22 13:39:39.243 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140037812163776] The fan_mode  is not a valid fan_mode: silent, low, medium, high, auto
```

**Comment by mill1000** [comment]
Hm, thanks. What's particularly odd to me is the error didn't originate from midea-ac-py, but from the API.

**Comment by parautenbach** [comment]
Oh, I see: `homeassistant.components.websocket_api.http.connection`.

Let me at least try and repeat the issue tomorrow: I'll restart HA again and then see if I can set the mode.

**Comment by mill1000** [comment]
Yeah let me know if it happens again, otherwise I'll close this issue in a few days.

**Comment by parautenbach** [comment]
I'm unable to reproduce this.

**Comment by mill1000** [comment]
Gotcha. Thanks for the update.
