### ISSUE TITLE
Unsupported capability.

### ISSUE THREAD

**Issue by jove01** [mill1000/midea-ac-py#80]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: msmart.device.AC.command
Source: custom_components/midea_ac/__init__.py:54
Integration: Midea Smart AC (documentation, issues)
First occurred: 22:01:01 (4 occurrences)
Last logged: 22:01:01

Unsupported capability. ID: 0x0009, Size: 1.
Unsupported capability. ID: 0x000A, Size: 1.

Let me know, if you need more information

**Comment by mill1000** [comment]
Thanks for the report. Those warning should be resolved in msmart-ng 2024.1.0 which is included in the latest release.
