### ISSUE TITLE
Unable to install more then one Midea AC

### ISSUE THREAD

**Issue by hfvdv** [mill1000/midea-ac-py#82]
I was able to add the first one just fine. For all the others ( 4 in total ) I followed the exact some process however receive the error that: "A connection could not be made."

**Comment by mill1000** [comment]
What method are you using to configure? Discovery or manual?

Anything in the logs?

**Comment by hfvdv** [comment]
Used discovery. I did see all of them however only the first in the list I was able to install. Nothing significant in the logs that o could see. Sent from my iPhoneOn 27 Jan 2024, at 22:03, Tucker Kern ***@***.***> wrote:﻿
What method are you using to configure? Discovery or manual?
Anything in the logs?

**Comment by mill1000** [comment]
Can you enable debug logging, try again and then post the logs?

**Comment by mill1000** [comment]
Closing due to a lack of information.
