### ISSUE TITLE
Midea AG-12NXD1.WIK

### ISSUE THREAD

**Issue by psyhomb** [mill1000/midea-ac-py#83]
Does this integration has support for Midea AG-12NXD1.WIK model?
Thank you and keep up the good work.

**Comment by mill1000** [comment]
Can't say for sure. Easiest way is to just test for support with https://github.com/mill1000/midea-msmart. 

Or if you know which app it uses that can be helpful.

**Comment by psyhomb** [comment]
The problem is I do not own mentioned AC and I would like to know if it is supported before I buy it.

**Comment by psyhomb** [comment]
It looks like it uses [Midea Air](https://play.google.com/store/apps/details?id=com.midea.aircondition.obm&hl=en_US) app.

**Comment by mill1000** [comment]
Based on the Midea Air app, it's likely that the device is compatible. I can't guarantee that of course.

**Comment by psyhomb** [comment]
Thank you!
