### ISSUE TITLE
HA 2024.02 warning

### ISSUE THREAD

**Issue by Theo16** [mill1000/midea-ac-py#84]
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Klimat (documentation, issues)
First occurred: 21:42:09 (3 occurrences)
Last logged: 21:42:09

Entity None (<class 'custom_components.midea_ac.climate.MideaClimateACDevice'>) implements HVACMode(s): fan_only, dry, cool, heat, auto, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/mill1000/midea-ac-py/issues

**Comment by mill1000** [comment]
Thanks for the report. I knew this was coming but was unsure if we'd be effected. I'll get an update out shortly.
