### ISSUE TITLE
Humidity Sensor on VIVAX AEHI

### ISSUE THREAD

**Issue by Kampos1** [mill1000/midea-ac-py#86]
This AC Air Condition use nethome application default and has sensors for indoor temperature,outdoor temperature and humidity sensor.All this sensors work in aplication.I used this integration in home asssitent and works great.Only missing this humidity sensor.How to add it.Thanks

**Comment by mill1000** [comment]
Hi,

The humidity sensor requires the "new" protocol which I have to implement: https://github.com/mill1000/midea-msmart/issues/97

I've started to look into it, but will need some testers to confirm it's operation.

**Comment by mill1000** [comment]
I have begun the work to implement this feature, but I will be need some testers to verify it. Are you available for some testing?
