### ISSUE TITLE
"Failed to setup" every time HA restarts

### ISSUE THREAD

**Issue by tecnobrat** [mill1000/midea-ac-py#90]
![image](https://github.com/mill1000/midea-ac-py/assets/145406/020bd767-4cc3-4334-9229-333923291fb6)

Version: 2024.2.1
HA Version: 2024.2.1

When I go to integrations I see that the integration setup failed, and this is in the logs:

```
Logger: homeassistant.config_entries
Source: config_entries.py:468
First occurred: February 11, 2024 at 5:47:28 PM (1 occurrences)
Last logged: February 11, 2024 at 5:47:28 PM

Config entry 'Bedroom AC' for midea_ac integration could not authenticate: Failed to authenticate with device.
```

```
This error originated from a custom integration.

Logger: msmart.base_device
Source: custom_components/midea_ac/__init__.py:39
Integration: Midea Smart AC (documentation, issues)
First occurred: February 11, 2024 at 5:47:28 PM (1 occurrences)
Last logged: February 11, 2024 at 5:47:28 PM

Authentication failed. Error: Connect timeout.
```

Reloading the integration fixes it until I restart HA again. Then it comes back.

**Comment by mill1000** [comment]
Can you enable debug logging and post the full logs after a restart?

What's your HA setup? Home Assistant OS? Docker?

**Comment by asifkassam** [comment]
Hi - same problem here, reloading config from the Integrations page manually work fine

WIith debug loggin enabled:

2024-02-16 07:21:12.838 ERROR (MainThread) [msmart.base_device] Authentication failed. Error: Connect timeout.
2024-02-16 07:21:12.840 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Guest Bedroom' for midea_ac integration could not authenticate: Failed to authenticate with device.
2024-02-16 07:21:12.841 ERROR (MainThread) [msmart.base_device] Authentication failed. Error: Connect timeout.
2024-02-16 07:21:12.841 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Office' for midea_ac integration could not authenticate: Failed to authenticate with device.

**Comment by mill1000** [comment]
Sorry you're having issues. Can you answer the above questions about your HA setup?

Those looks don't look like debugging was enabled (or I don't log nearly enough helpful information!).

**Comment by asifkassam** [comment]
Sorry, my bad with the debug logs - will redo, but not able to replicate it at present - last 3 reboots have loaded the devices fine

Running HA OS on a Pi4b

I'll upload the correct logs if it happens again

**Comment by asifkassam** [comment]
[home-assistant_midea_ac_2024-02-16T08-02-45.973Z.log](https://github.com/mill1000/midea-ac-py/files/14308151/home-assistant_midea_ac_2024-02-16T08-02-45.973Z.log)

**Comment by asifkassam** [comment]
I rolled back my HA Core version to 2024.1.6 and the problem has gone away - it appears possibly related to https://github.com/home-assistant/core/issues/109903 which also went away when rolling back to 2024.1.6

**Comment by mill1000** [comment]
Thanks for the logs. For whatever reason the network doesn't appear to be up when your HA restarts, but it also looks like I should be implementing a "reauth" flow to allow the integration a chance to connect again.

https://developers.home-assistant.io/docs/integration_setup_failures/

**Comment by mill1000** [comment]
Just released a new version that I'm hoping will help you with your problem. Let me know either way.

**Comment by LexanRed** [comment]
I have the same problem. Whenever home assistant restarts, I get authentication erros a few times, then it just works.

**Comment by driu8808** [comment]
Hi,
I have the same problem too but I've temporary resolved defining a simple automation that reload the entities after homeassistant restart.
Something like:
```
alias: Midea
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: homeassistant.reload_config_entry
    target:
      device_id:
        - ************************
    data: {}
mode: single
```
I hope can be helpful.

**Comment by mill1000** [comment]
Have you all updated to 2024.2.3?

**Comment by driu8808** [comment]
I didn't notice there was a new version after 2024.2.2. I updated now and it seems to work fine for me.
Thanks

**Comment by mill1000** [comment]
Yeah I don't blame you. I released them within a few hours of each other since I realized I left a bug in 2024.2.2

**Comment by tecnobrat** [comment]
Seems to be working for me now, updated and restarted and it looks to be working.

**Comment by mill1000** [comment]
👍 Glad to hear it. Let me know if anything else comes up.

**Comment by snichita** [comment]
hello, the issue started again, with the Not loaded error
![IMG_0886](https://github.com/user-attachments/assets/052cc6bf-3d1a-4d4a-9a40-c63a4d1c50bf)

**Comment by mill1000** [comment]
@snichita you have not provided sufficient information for me to debug. I am not even certain what your problem is.

Please,
1. Create a new issue, describing your specific problem.
2. Provide complete debug logs showing the issue.
