### ISSUE TITLE
Publish Custom Fan Speed Slider into HomeKit. 

### ISSUE THREAD

**Issue by msdurex** [mill1000/midea-ac-py#91]
I noticed that there is a custom control slider for fan speed control. Is there any workaround that I could publish this slider to HomeKit via HomeBridge? It will be nice if it also would integrate within native HomeKit thermostat fan speed slider. HomeBridge kind of makes fan speed as a HomeKit fan. 
<img width="574" alt="Screenshot 2024-02-16 at 3 31 13 AM" src="https://github.com/mill1000/midea-ac-py/assets/19863959/5b886d0e-5f2f-482c-87fe-fd9fe1f0b4cf">

**Comment by mill1000** [comment]
Hi,

Are you using something like the [HomeKit Bridge](https://www.home-assistant.io/integrations/homekit/)? or just HomeBridge?

I'm not too familiar with either option frankly, but I'd guess that the limitation is in those systems

**Comment by msdurex** [comment]
Yes, I am currently running Home Assistant and bridge to HomeKit with HomeKit bridge.

**Comment by mill1000** [comment]
Gotcha. I don't think there's anything I can do from the integration to help you.

I think the HomeKit Bridge integration would need to be updated to allow "linking" an entity to the climate entity.

The only other thing I can think of would be to create the fan speed slider as an actual fan entity, but again it would be distinct from the climate entity.

**Comment by msdurex** [comment]
I see. It would require two things happen in the same time. Firstly the Home Assistant supports percentage fan speed slider. Secondly HomeKit Bridge changes to normal thermostat fan speed control and swing mode control.
