### ISSUE TITLE
Device becomes unavailable for a couple of seconds

### ISSUE THREAD

**Issue by JMCSN** [mill1000/midea-ac-py#92]
Hello, 

This integration is working well except that my connection keeps getting unavailable since the install. See picture attached for log.
Am I doing something wrong here? (HA has been restarted multiple times)

![Schermafbeelding 2024-02-16 144201](https://github.com/mill1000/midea-ac-py/assets/126153403/5ee2203d-80b5-4983-9545-2d114ca2ab1c)

**Comment by mill1000** [comment]
Probably an easy fix. Try setting the [Maximum Connection Lifetime](https://github.com/mill1000/midea-ac-py#integration-options) setting to 90.

**Comment by JMCSN** [comment]
Hello

 

 

This did the trick, completely looked over this option.

Great addon by the way.

 

 

Thanks!

 



 

Van: Tucker Kern ***@***.***> 
Verzonden: vrijdag 16 februari 2024 19:11
Aan: mill1000/midea-ac-py ***@***.***>
CC: JMCSN ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mill1000/midea-ac-py] Device becomes unavailable for a couple of seconds (Issue #92)

 

Probably an easy fix. Try setting the Maximum Connection Lifetime <https://github.com/mill1000/midea-ac-py#integration-options>  setting to 90.

**Comment by mill1000** [comment]
No problem. Glad it worked for you.

**Comment by JMCSN** [comment]
Hello

 

 

Excuse me for bothering you again. Everything worked fine but one day ago the configuration just stopped working without me touching anything.

Reloading the config and restarting does not fix the issue.

 

 

Kind regards.

 



 

Van: Tucker Kern ***@***.***> 
Verzonden: zaterdag 17 februari 2024 16:53
Aan: mill1000/midea-ac-py ***@***.***>
CC: JMCSN ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mill1000/midea-ac-py] Device becomes unavailable for a couple of seconds (Issue #92)

 

No problem. Glad it worked for you.

**Comment by mill1000** [comment]
Can you provide logs from Home Assistant?

**Comment by mill1000** [comment]
I don't know of a way to only download the midea logs. If you are uncomfortable posting them here you can always email them to me.

**Comment by JMCSN** [comment]
[home-assistant_midea_ac_2024-02-24T09-55-36.854Z.log](https://github.com/mill1000/midea-ac-py/files/14392391/home-assistant_midea_ac_2024-02-24T09-55-36.854Z.log)
Please find the debug log attached.

**Comment by mill1000** [comment]
This log looks like you are having general network issues. There's multiple integrations throwing errors about being unable to reach the network.

If the network is otherwise working, perhaps the Midea device changed it's IP? You would need to reconfigure the device.

**Comment by JMCSN** [comment]
Ok, I’ll check if something changed regarding the IP address. Maybe better to use a static ip.

 

 

Kind regards.

 



 

Van: Tucker Kern ***@***.***> 
Verzonden: zaterdag 24 februari 2024 19:07
Aan: mill1000/midea-ac-py ***@***.***>
CC: JMCSN ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mill1000/midea-ac-py] Device becomes unavailable for a couple of seconds (Issue #92)

 

This log looks like you are having general network issues. There's multiple integrations throwing errors about being unable to reach the network.

If the network is otherwise working, perhaps the Midea device changed it's IP? You would need to remove and re-add the device.
