### ISSUE TITLE
Starting AC in cool mode

### ISSUE THREAD

**Issue by coarsy** [mill1000/midea-ac-py#97]
Is there a way to start the AC always in cool mode instead of the heat mode? Every time I switch on my device it always starts in head mode.

**Comment by mill1000** [comment]
How are you switching it on? I typically use just select cool mode directly from the drop down.

**Comment by coarsy** [comment]
I switch it on over a mushroom climate card. There is no dropdown available. 

This is the off-state:
![mushroom_climate](https://github.com/mill1000/midea-ac-py/assets/2741933/7ab0bc5b-a0c8-47b7-8a92-83e8be82d20d)

It turns to this when clicking on it:
![mushroom_climate_on](https://github.com/mill1000/midea-ac-py/assets/2741933/bba3a787-12d5-4ba4-8480-ab61d7ddebcf)

It always gets into the heat-mode. I found no setup cool mode as default to start.

**Comment by mill1000** [comment]
Gotcha. Does the mushroom card default to turning the device on/off or did you define a tap action?

This integration doesn't define explicit `turn_on` and `turn_off` methods, but apparently inherits implicit ones since it supports `HVACMode.OFF`.

The implicit ones are defined [here](https://github.com/home-assistant/core/blob/928458160e0cc2c6fac739aa078f1cbe180fc465/homeassistant/components/climate/__init__.py#L746-L768), but the most important part is this:
```python
# Fake turn on
for mode in (HVACMode.HEAT_COOL, HVACMode.HEAT, HVACMode.COOL):
    if mode not in self.hvac_modes:
        continue
    await self.async_set_hvac_mode(mode)
    return
```
which defaults to the first supported HVACMode, which is heat.

I'll look into defining property turn_off/turn_on methods and I think this should fix your problem.

**Comment by mill1000** [comment]
I think I've got a fixed lined up in #98. Would you be able to test? My units are offline for the season.

**Comment by coarsy** [comment]
Good morning, how could I test this? Just wanted to replace the files, but in my installed version the __init__.py has only 101 rows. And this is really few in comparison with the new file.

**Comment by coarsy** [comment]
So, I just replaced the climate.py and restarted HA but the AC is still starting in heat mode.

**Comment by mill1000** [comment]
Never as easy as I hoped. Can you enable debug logging, turn the AC off from Cool mode and then back on?

**Comment by coarsy** [comment]
Hi, here is the debuglogfile for you:

[debug_mssmart.txt](https://github.com/mill1000/midea-ac-py/files/14451423/debug_mssmart.txt)

**Comment by mill1000** [comment]
Did you restart HA after copying the `climate.py` over?

Also this comment doesn't make sense

> Just wanted to replace the files, but in my installed version the init.py has only 101 rows. And this is really few in comparison with the new file.

The length of `__init__.py` in this project is 101 lines. If your version was different I think it means you were in the wrong path.

**Comment by coarsy** [comment]
This comment is wrong. Just ignore it. Copied the climate.py and restarted HA.

**Comment by coarsy** [comment]
If I add the code to climate.py the integration won't start anymor. Could you tell me the exact line number to add the code snippet to?

**Comment by coarsy** [comment]
[home-assistant_midea_ac.log](https://github.com/mill1000/midea-ac-py/files/14464087/home-assistant_midea_ac.log)

This is the current log. I activated AC, switched to cool mode after it starts into heat mode. Then turned it off an did the same again.

**Comment by mill1000** [comment]
Thanks.

Your latest logs don't have the expected statements in them.

I also tested this change locally (by faking a device) and it works as expected. 

So I'm lead to believe you have not updated the component properly, and that's why it's still showing the issue.

**Comment by coarsy** [comment]
Good evening Tucker, you're right! I compared the files and the old climate.py without the change was loaded again. Now everything works as expected. Where can I buy you a coffee?

**Comment by mill1000** [comment]
Great! Thanks for confirming. I'll get this change merged and released ASAP.

I have Github Sponsers setup on this repo if that works, but no pressure.
